// Sarasota Community Resources Database
const resourcesDatabase = [
// Libraries
  {
    id: 1,
    name: "Selby Public Library",
    category: "Libraries",
    description: "Downtown Sarasota's main public library with books, digital resources, and community events.",
    address: "1331 1st St, Sarasota, FL 34236",
    phone: "(941) 861-1100",
    website: "https://www.scgov.net/government/departments/libraries/locations/selby-library",
    lat: 27.3366,
    lng: -82.5432,
    hours: "Mon-Thu: 10am-8pm, Fri-Sat: 10am-5pm, Sun: 1pm-5pm",
    tags: ["Education", "Community", "Events"],
    services: ["Free WiFi", "Computer Lab", "Events", "Meeting Rooms"]
  },
{
    id: 2,
    name: "Fruitville Public Library",
    category: "Libraries",
    description: "Community library with programs for all ages.",
    address: "100 Coburn Rd, Sarasota, FL 34240",
    phone: "(941) 861-2500",
    website: "https://www.scgov.net/government/departments/libraries/locations/fruitville-library",
    lat: 27.3361,
    lng: -82.4082,
    hours: "Mon-Thu: 10am-8pm, Fri-Sat: 10am-5pm, Sun: 1pm-5pm",
    tags: ["Education", "Children", "Community"],
    services: ["Children's Programs", "Book Lending", "Events"]
  },
{
    id: 3,
    name: "North Sarasota Library",
    category: "Libraries",
    description: "Public library serving North Sarasota with books, computers, and programs.",
    address: "2801 Newtown Blvd, Sarasota, FL 34234",
    phone: "(941) 861-1360",
    website: "https://www.scgov.net/government/departments/libraries/locations/north-sarasota-library",
    lat: 27.3661,
    lng: -82.5302,
    hours: "Mon-Thu: 10am-8pm, Fri-Sat: 10am-5pm, Sun: 1pm-5pm",
    tags: ["Education", "Community"],
    services: ["Computer Access", "Book Lending", "Events"]
  },
{
    id: 4,
    name: "Sarasota Memorial Health Care System",
    category: "Healthcare",
    description: "Comprehensive hospital and specialty care.",
    address: "1700 S Tamiami Trail, Sarasota, FL 34239",
    phone: "(941) 917-9000",
    website: "https://www.smh.com/",
    lat: 27.3357,
    lng: -82.5339,
    hours: "24/7",
    tags: ["Hospital", "Specialty Care", "Emergency"],
    services: ["Emergency Room", "Specialists", "Testing"]
  },
{
    id: 5,
    name: "Centerstone Sarasota",
    category: "Healthcare",
    description: "Mental health and substance abuse treatment services.",
    address: "379 6th Ave W, Bradenton, FL 34205",
    phone: "(941) 782-4150",
    website: "https://centerstone.org/locations/florida/",
    lat: 27.4975,
    lng: -82.5707,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Mental Health", "Substance Abuse", "Healthcare"],
    services: ["Therapy", "Psychiatry", "Substance Abuse Treatment", "Crisis Support"]
  },
// Real Transitional Housing
  {
    id: 6,
    name: "Harvest House Transitional Housing",
    category: "Shelters",
    description: "Transitional housing and supportive services for families and veterans.",
    address: "3650 17th St, Sarasota, FL 34235",
    phone: "(941) 953-3154",
    website: "https://www.harvesthousecenters.org/",
    lat: 27.3417,
    lng: -82.4962,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Housing", "Support Services", "Veterans"],
    services: ["Transitional Housing", "Case Management", "Support Services"]
  },
{
    id: 7,
    name: "Resurrection House",
    category: "Shelters",
    description: "Day resource center for the homeless, offering showers, laundry, and case management.",
    address: "507 Kumquat Ct, Sarasota, FL 34236",
    phone: "(941) 365-3759",
    website: "https://resurrectionhousesarasota.org/",
    lat: 27.3377,
    lng: -82.5436,
    hours: "Mon-Fri: 8am-12pm",
    tags: ["Homeless Services", "Day Center", "Support"],
    services: ["Showers", "Laundry", "Case Management"]
  },
// Job Services
  {
    id: 8,
    name: "CareerSource Suncoast",
    category: "Job Services",
    description: "Workforce development, job search, and training for Sarasota and Manatee counties.",
    address: "3660 N Washington Blvd, Sarasota, FL 34234",
    phone: "(941) 358-4200",
    website: "https://careersourcesuncoast.com/",
    lat: 27.3731,
    lng: -82.5282,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Job Training", "Employment", "Career Services"],
    services: ["Job Search", "Career Counseling", "Resume Help", "Training"]
  },
// Parks & Recreation
  {
    id: 9,
    name: "Siesta Beach",
    category: "Parks",
    description: "Famous white-sand public beach with swimming, volleyball, and picnic areas.",
    address: "948 Beach Rd, Sarasota, FL 34242",
    phone: "(941) 861-5000",
    website: "https://www.scgov.net/government/departments/parks-recreation-and-natural-resources/parks/siesta-beach",
    lat: 27.2671,
    lng: -82.5461,
    hours: "6am-10pm",
    tags: ["Beach", "Recreation", "Family"],
    services: ["Swimming", "Picnic Areas", "Restrooms", "Parking"]
  },
{
    id: 10,
    name: "Myakka River State Park",
    category: "Parks",
    description: "Large state park with hiking, camping, and wildlife viewing.",
    address: "13208 State Rd 72, Sarasota, FL 34241",
    phone: "(941) 361-6511",
    website: "https://www.floridastateparks.org/parks-and-trails/myakka-river-state-park",
    lat: 27.2451,
    lng: -82.3166,
    hours: "8am-sunset",
    tags: ["Camping", "Hiking", "Wildlife"],
    services: ["Trails", "Canoe Rentals", "Picnic Areas"]
  },
{
    id: 11,
    name: "Lido Beach",
    category: "Parks",
    description: "Popular beach with white sand and family amenities.",
    address: "400 Benjamin Franklin Dr, Sarasota, FL 34236",
    phone: "(941) 861-5000",
    website: "https://www.scgov.net/government/departments/parks-recreation-and-natural-resources/parks/lido-beach",
    lat: 27.3112,
    lng: -82.5771,
    hours: "6am-11pm",
    tags: ["Beach", "Recreation", "Family"],
    services: ["Parking", "Facilities", "Lifeguard"]
  },
// Public Transit
  {
    id: 12,
    name: "Sarasota County Area Transit (SCAT)",
    category: "Transit",
    description: "Public bus transportation serving Sarasota County.",
    address: "5303 Pinkney Ave, Sarasota, FL 34233",
    phone: "(941) 861-1234",
    website: "https://www.scgov.net/government/scat",
    lat: 27.2856,
    lng: -82.4732,
    hours: "Mon-Sat: 5am-10pm, Sun: 6am-9pm",
    tags: ["Transportation", "Public Transit", "Accessible"],
    services: ["Bus Service", "Paratransit", "Route Planning"]
  },
{
    id: 13,
    name: "Meals on Wheels Sarasota",
    category: "Food Services",
    description: "Delivers nutritious meals to homebound seniors and individuals in need.",
    address: "421 N Lime Ave, Sarasota, FL 34237",
    phone: "(941) 366-6693",
    website: "https://www.mealsonwheelsofsarasota.org/",
    lat: 27.3402,
    lng: -82.5227,
    hours: "Mon-Fri: 8am-4pm",
    tags: ["Senior Services", "Nutrition", "Assistance"],
    services: ["Meal Delivery", "Nutrition Counseling"]
  },
// Youth Services
  {
    id: 14,
    name: "Boys & Girls Clubs of Sarasota and DeSoto Counties",
    category: "Youth Services",
    description: "After-school and summer programs for youth, including mentoring and enrichment.",
    address: "3100 Fruitville Rd, Sarasota, FL 34237",
    phone: "(941) 366-3911",
    website: "https://bgcsdc.org/",
    lat: 27.3347,
    lng: -82.5052,
    hours: "Mon-Fri: 2pm-7pm",
    tags: ["Youth", "Education", "Recreation"],
    services: ["After School Programs", "Mentoring", "Sports"]
  },
// Senior Services
  {
    id: 15,
    name: "Senior Friendship Centers",
    category: "Senior Services",
    description: "Community center offering programs and activities for seniors.",
    address: "1888 Brother Geenen Way, Sarasota, FL 34236",
    phone: "(941) 955-2122",
    website: "https://friendshipcenters.org/",
    lat: 27.3317,
    lng: -82.5342,
    hours: "Mon-Fri: 8am-4:30pm",
    tags: ["Senior Services", "Community", "Recreation"],
    services: ["Recreation Programs", "Classes", "Lunch Programs"]
  },
{
    id: 16,
    name: "Area Agency on Aging for Southwest Florida",
    category: "Senior Services",
    description: "Advocates for elderly residents and coordinates care services.",
    address: "2830 Winkler Ave #112, Fort Myers, FL 33916",
    phone: "(866) 413-5337",
    website: "https://www.aaaswfl.org/",
    lat: 26.6236,
    lng: -81.8498,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Senior Services", "Advocacy", "Care"],
    services: ["Care Coordination", "Advocacy", "Support Groups"]
  },
// Community Organizations
  {
    id: 17,
    name: "United Way Suncoast (Sarasota)",
    category: "Community Services",
    description: "Coordinating philanthropic support and community programs for Sarasota.",
    address: "1800 2nd St Suite 102, Sarasota, FL 34236",
    phone: "(941) 366-2686",
    website: "https://unitedwaysuncoast.org/",
    lat: 27.3351,
    lng: -82.5392,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Community", "Charity", "Support"],
    services: ["Fundraising", "Volunteer Opportunities", "Community Programs"]
  },
{
    id: 18,
    name: "Sarasota NAACP",
    category: "Community Services",
    description: "Advancing civil rights and equality in Sarasota.",
    address: "1750 17th St, Sarasota, FL 34234",
    phone: "(941) 355-2097",
    website: "https://sarasotanaacp.org/",
    lat: 27.3551,
    lng: -82.5267,
    hours: "By appointment",
    tags: ["Community", "Civil Rights", "Advocacy"],
    services: ["Advocacy", "Community Events", "Education"]
  },
{
    id: 19,
    name: "Sarasota NAACP",
    category: "Community Services",
    description: "Advancing civil rights and equality",
    address: "1923 Martin Luther King Jr Way, Sarasota, FL 34234",
    phone: "(941) 957-0521",
    website: "https://sarasotanaacp.org",
    lat: 27.3203,
    lng: -82.5040,
    hours: "By appointment",
    tags: ["Community", "Civil Rights", "Advocacy"],
    services: ["Advocacy", "Community Events", "Education"]
  },
{
    id: 20,
    name: "Sarasota County Volunteer Center",
    category: "Community Services",
    description: "Connecting volunteers with community organizations",
    address: "1300 Vista Park Blvd, Sarasota, FL 34236",
    phone: "(941) 341-9500",
    website: "https://sarasotavolunteer.org",
    lat: 27.3516,
    lng: -82.5209,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Community", "Volunteer", "Support"],
    services: ["Volunteer Placement", "Training", "Community Connection"]
  },
// Childcare & Family Services
  {
    id: 21,
    name: "Sarasota County Early Childhood Programs",
    category: "Family Services",
    description: "Pre-K and early childhood education programs",
    address: "4747 Beneva Rd, Sarasota, FL 34233",
    phone: "(941) 921-6500",
    website: "https://www.sarasotacountyschools.net",
    lat: 27.3047,
    lng: -82.4468,
    hours: "Mon-Fri: 7am-6pm",
    tags: ["Childcare", "Education", "Family"],
    services: ["Pre-K Programs", "Day Care", "Special Needs Services"]
  },
{
    id: 22,
    name: "State College of Florida",
    category: "Education",
    description: "Community college with vocational and academic programs",
    address: "6505 College Circle, Bradenton, FL 34203",
    phone: "(941) 752-5000",
    website: "https://www.scf.edu",
    lat: 27.4778,
    lng: -82.5712,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Education", "Community College", "Vocational"],
    services: ["Associate Degrees", "Vocational Training", "Career Services"]
  },
{
    id: 23,
    name: "Florida Supreme Court - Pro Bono Program",
    category: "Legal Services",
    description: "Volunteer lawyers providing free legal services",
    address: "1920 N Orange Ave, Sarasota, FL 34236",
    phone: "(941) 955-8747",
    website: "https://www.floridabar.org",
    lat: 27.3533,
    lng: -82.5150,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Legal Services", "Volunteer", "Assistance"],
    services: ["Pro Bono Legal Help", "Consultation"]
  },
// Substance Abuse Services
  {
    id: 24,
    name: "Centerstone Recovery & Prevention Services",
    category: "Healthcare",
    description: "Substance abuse treatment and recovery support",
    address: "3321 Proctor St, Sarasota, FL 34234",
    phone: "(941) 954-1754",
    website: "https://centerstone.org",
    lat: 27.3239,
    lng: -82.5029,
    hours: "Mon-Fri: 8am-6pm",
    tags: ["Substance Abuse", "Treatment", "Recovery"],
    services: ["Treatment Programs", "Recovery Support", "Counseling"]
  },
{
    id: 25,
    name: "12-Step Support Groups",
    category: "Support Services",
    description: "Community recovery support meetings",
    address: "Multiple locations in Sarasota",
    phone: "(941) 955-4922",
    website: "https://www.aa.org",
    lat: 27.3365,
    lng: -82.5297,
    hours: "Various times daily",
    tags: ["Recovery", "Support", "Community"],
    services: ["AA Meetings", "NA Meetings", "Al-Anon"]
  },
// Disability Services
  {
    id: 26,
    name: "Sarasota Disability Resources",
    category: "Support Services",
    description: "Support services for individuals with disabilities",
    address: "1920 Market St, Sarasota, FL 34236",
    phone: "(941) 953-2545",
    website: "https://www.scgov.net/disability",
    lat: 27.3344,
    lng: -82.5309,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Disability", "Support", "Accessibility"],
    services: ["Case Management", "Employment Support", "Advocacy", "Recreation"]
  },
// Veterans Services
  {
    id: 27,
    name: "Veterans Service Office - Sarasota County",
    category: "Support Services",
    description: "Services and benefits assistance for veterans",
    address: "1660 Ringling Blvd, Sarasota, FL 34236",
    phone: "(941) 861-2500",
    website: "https://www.scgov.net/veterans",
    lat: 27.3428,
    lng: -82.5310,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Veterans", "Benefits", "Support"],
    services: ["Benefits Assistance", "Counseling", "Housing Support", "Employment"]
  },
{
    id: 28,
    name: "American Legion Post 24",
    category: "Support Services",
    description: "Community organization serving veterans",
    address: "2409 Bay St, Sarasota, FL 34234",
    phone: "(941) 953-1177",
    website: "https://www.legion.org",
    lat: 27.3203,
    lng: -82.5150,
    hours: "Mon-Sun: 12pm-11pm",
    tags: ["Veterans", "Community", "Social"],
    services: ["Social Events", "Veteran Support", "Community Programs"]
  },
// Childcare & Family Services
  {
    id: 29,
    name: "Sarasota County Early Childhood Programs",
    category: "Family Services",
    description: "Pre-K and early childhood education programs",
    address: "4747 Beneva Rd, Sarasota, FL 34233",
    phone: "(941) 921-6500",
    website: "https://www.sarasotacountyschools.net",
    lat: 27.3047,
    lng: -82.4468,
    hours: "Mon-Fri: 7am-6pm",
    tags: ["Childcare", "Education", "Family"],
    services: ["Pre-K Programs", "Day Care", "Special Needs Services"]
  },
// Real Recreation Provider
  {
    id: 30,
    name: "Kayaking SRQ Tours & Rentals",
    category: "Recreation",
    description: "Guided kayak tours and rentals in Sarasota's mangroves and bay.",
    address: "1265 Old Stickney Point Rd, Sarasota, FL 34242",
    phone: "(941) 400-2740",
    website: "https://kayakingsrq.com/",
    lat: 27.2467,
    lng: -82.5292,
    hours: "Daily: 8am-5pm",
    tags: ["Water Sports", "Recreation", "Tours"],
    services: ["Kayak Rentals", "Guided Tours", "Lessons"]
  },
// Real Transitional Housing
  {
    id: 31,
    name: "Harvest House Transitional Housing",
    category: "Shelters",
    description: "Transitional housing and supportive services for families and veterans.",
    address: "3650 17th St, Sarasota, FL 34235",
    phone: "(941) 953-3154",
    website: "https://www.harvesthousecenters.org/",
    lat: 27.3417,
    lng: -82.4962,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Housing", "Support Services", "Veterans"],
    services: ["Transitional Housing", "Case Management", "Support Services"]
  },
// Real Recovery Housing
  {
    id: 32,
    name: "First Step of Sarasota",
    category: "Shelters",
    description: "Recovery housing and addiction treatment services.",
    address: "4579 Northgate Ct, Sarasota, FL 34234",
    phone: "(941) 366-5333",
    website: "https://www.fsos.org/",
    lat: 27.3731,
    lng: -82.5292,
    hours: "24/7",
    tags: ["Recovery", "Housing", "Support"],
    services: ["Recovery Housing", "Support Groups", "Counseling"]
  },
{
    id: 33,
    name: "Sarasota Memorial Health Care System",
    category: "Healthcare",
    description: "Comprehensive hospital and specialty care.",
    address: "1700 S Tamiami Trail, Sarasota, FL 34239",
    phone: "(941) 917-9000",
    website: "https://www.smh.com/",
    lat: 27.3357,
    lng: -82.5339,
    hours: "24/7",
    tags: ["Hospital", "Specialty Care", "Emergency"],
    services: ["Emergency Room", "Specialists", "Testing"]
  },
// Real Event Venues
  {
    id: 34,
    name: "Van Wezel Performing Arts Hall",
    category: "Recreation",
    description: "Major performing arts venue for concerts, theater, and events.",
    address: "777 N Tamiami Trail, Sarasota, FL 34236",
    phone: "(941) 263-6799",
    website: "https://www.vanwezel.org/",
    lat: 27.3436,
    lng: -82.5467,
    hours: "Box office: Mon-Fri: 10am-4pm",
    tags: ["Venue", "Events", "Performance"],
    services: ["Events", "Performances", "Rentals"]
  },
  {
    id: 35,
    name: "All Faiths Food Bank",
    category: "Food Services",
    description: "The only food bank and largest hunger relief organization in Sarasota and DeSoto counties, providing food to those in need.",
    address: "8171 Blaikie Ct, Sarasota, FL 34240",
    phone: "(941) 379-6333",
    website: "https://allfaithsfoodbank.org/",
    lat: 27.3340,
    lng: -82.4330,
    hours: "Mon-Thu: 8am-5pm, Fri: 8am-12pm, Sat-Sun: Closed",
    tags: ["Food Pantry", "Charity", "Hunger Relief"],
    services: ["Food Distribution", "Mobile Pantry", "Benefits Assistance"]
  },
  {
    id: 36,
    name: "Goodwill Manasota (Job Connection)",
    category: "Job Services",
    description: "Provides job training, employment placement services, and community-based programs for people with disabilities or other barriers to work.",
    address: "2705 51st Ave E, Bradenton, FL 34203",
    phone: "(941) 355-2721",
    website: "https://experiencegoodwill.org/",
    lat: 27.4410,
    lng: -82.5400,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Employment", "Training", "Nonprofit"],
    services: ["Job Placement", "Career Counseling", "Skills Training"]
  },
  {
    id: 37,
    name: "New College of Florida",
    category: "Education",
    description: "A public liberal arts honors college focused on individualized education and undergraduate research.",
    address: "5800 Bay Shore Rd, Sarasota, FL 34243",
    phone: "(941) 487-5000",
    website: "https://www.ncf.edu/",
    lat: 27.3850,
    lng: -82.5600,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["College", "University", "Public Education"],
    services: ["Undergraduate Degrees", "Research", "Public Events"]
  },
  {
    id: 38,
    name: "CoreSRQ (formerly Sarasota YMCA)",
    category: "Recreation",
    description: "A non-profit organization dedicated to building strong kids, strong families, and strong communities through fitness and wellness programs.",
    address: "1075 S Euclid Ave, Sarasota, FL 34237",
    phone: "(941) 955-8194",
    website: "https://www.coresrq.org/",
    lat: 27.3200,
    lng: -82.5300,
    hours: "Mon-Fri: 5am-9pm, Sat: 7am-5pm, Sun: 10am-4pm",
    tags: ["Gym", "Fitness", "Swimming", "Youth Sports"],
    services: ["Fitness Classes", "Swim Lessons", "Youth Camps"]
  },
  {
    id: 39,
    name: "Legal Aid of Manasota",
    category: "Legal Services",
    description: "Provides free civil legal services to low-income residents of Sarasota and Manatee counties.",
    address: "1900 Main St Ste 302, Sarasota, FL 34236",
    phone: "(941) 366-0038",
    website: "https://www.legalaidofmanasota.org/",
    lat: 27.3360,
    lng: -82.5390,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Legal Help", "Pro Bono", "Civil Law"],
    services: ["Legal Advice", "Representation", "Community Education"]
  },
  {
    id: 40,
    name: "SPARCC (Safe Place and Rape Crisis Center)",
    category: "Support Services",
    description: "The only state-certified domestic violence center and rape crisis center for Sarasota and DeSoto counties.",
    address: "2139 Main St, Sarasota, FL 34237",
    phone: "(941) 365-0208",
    website: "https://www.sparcc.net/",
    lat: 27.3360,
    lng: -82.5350,
    hours: "24/7 Helpline",
    tags: ["Domestic Violence", "Crisis Support", "Shelter"],
    services: ["Emergency Shelter", "Counseling", "Legal Advocacy", "24-Hour Helpline"]
  },
  {
    id: 41,
    name: "Habitat for Humanity Sarasota",
    category: "Community Services",
    description: "Partners with families in need of affordable housing to build safe and sustainable homes.",
    address: "1757 N East Ave, Sarasota, FL 34234",
    phone: "(941) 365-0700",
    website: "https://www.habitatsarasota.com/",
    lat: 27.3480,
    lng: -82.5320,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Housing", "Volunteering", "Affordable Homes"],
    services: ["Home Building", "ReStore", "Housing Assistance"]
  },
  {
    id: 42,
    name: "First Physicians Group (Urgent Care)",
    category: "Healthcare",
    description: "Urgent Care centers providing convenient access to medical care for non-life-threatening illnesses and injuries.",
    address: "5360 University Pkwy, Sarasota, FL 34243",
    phone: "(941) 917-1234",
    website: "https://www.firstphysiciansgroup.com/",
    lat: 27.3880,
    lng: -82.4630,
    hours: "Daily: 8am-8pm",
    tags: ["Medical", "Doctor", "Walk-in"],
    services: ["Urgent Care", "X-Rays", "Lab Testing"]
  },
  {
    id: 43,
    name: "The Ringling Museum",
    category: "Recreation",
    description: "The State Art Museum of Florida, featuring the John and Mable Ringling Museum of Art, Circus Museum, and Ca' d'Zan.",
    address: "5401 Bay Shore Rd, Sarasota, FL 34243",
    phone: "(941) 359-5700",
    website: "https://www.ringling.org/",
    lat: 27.3820,
    lng: -82.5600,
    hours: "Daily: 10am-5pm",
    tags: ["Museum", "Art", "History", "Gardens"],
    services: ["Exhibits", "Tours", "Education Programs"]
  },
  {
    id: 44,
    name: "Marie Selby Botanical Gardens",
    category: "Parks",
    description: "A bayfront botanical garden dedicated to the study and conservation of epiphytic plants.",
    address: "1534 Mound St, Sarasota, FL 34236",
    phone: "(941) 366-5731",
    website: "https://selby.org/",
    lat: 27.3270,
    lng: -82.5410,
    hours: "Daily: 10am-5pm",
    tags: ["Gardens", "Nature", "Botany"],
    services: ["Garden Tours", "Events", "Research"]
  },
  {
    id: 45,
    name: "Mote Marine Laboratory & Aquarium",
    category: "Education",
    description: "A world-class marine research institution and public aquarium.",
    address: "1600 Ken Thompson Pkwy, Sarasota, FL 34236",
    phone: "(941) 388-4441",
    website: "https://mote.org/",
    lat: 27.3330,
    lng: -82.5700,
    hours: "Daily: 9:30am-5pm",
    tags: ["Aquarium", "Marine Science", "Wildlife"],
    services: ["Exhibits", "Research", "Eco-Tours"]
  },
  {
    id: 46,
    name: "Sarasota Opera",
    category: "Recreation",
    description: "A professional opera company presenting world-class performances in the historic Sarasota Opera House.",
    address: "61 N Pineapple Ave, Sarasota, FL 34236",
    phone: "(941) 328-1300",
    website: "https://www.sarasotaopera.org/",
    lat: 27.3370,
    lng: -82.5420,
    hours: "Box Office: Mon-Fri 10am-4pm",
    tags: ["Arts", "Music", "Performance"],
    services: ["Opera Performances", "Youth Opera", "Tours"]
  },
  {
    id: 47,
    name: "Oscar Scherer State Park",
    category: "Parks",
    description: "A large state park preserving scrub-jay habitat, offering hiking, camping, and swimming.",
    address: "1843 S Tamiami Trail, Osprey, FL 34229",
    phone: "(941) 483-5956",
    website: "https://www.floridastateparks.org/parks-and-trails/oscar-scherer-state-park",
    lat: 27.1700,
    lng: -82.4600,
    hours: "Daily: 8am-Sundown",
    tags: ["Hiking", "Camping", "Nature", "Wildlife"],
    services: ["Trails", "Campsites", "Picnic Areas"]
  },
  {
    id: 48,
    name: "Nathan Benderson Park",
    category: "Parks",
    description: "A 600-acre community park hosting world-class rowing events and recreational activities.",
    address: "5851 Nathan Benderson Cir, Sarasota, FL 34235",
    phone: "(941) 358-7275",
    website: "https://nathanbendersonpark.org/",
    lat: 27.3750,
    lng: -82.4500,
    hours: "Daily: 6am-8pm",
    tags: ["Rowing", "Running", "Playground"],
    services: ["Event Hosting", "Boat Rentals", "Trails"]
  },
  {
    id: 49,
    name: "Doctors Hospital of Sarasota",
    category: "Healthcare",
    description: "A full-service, acute care facility serving Sarasota and the surrounding communities.",
    address: "5731 Bee Ridge Rd, Sarasota, FL 34233",
    phone: "(941) 342-1100",
    website: "https://doctorsofsarasota.com/",
    lat: 27.2960,
    lng: -82.4630,
    hours: "24/7 Emergency",
    tags: ["Hospital", "Emergency", "Medical"],
    services: ["Emergency Room", "Surgery", "Inpatient Care"]
  },
  {
    id: 50,
    name: "Women's Resource Center",
    category: "Support Services",
    description: "Empowering women with programs and services for mental health, career success, and personal growth.",
    address: "340 S Tuttle Ave, Sarasota, FL 34237",
    phone: "(941) 366-1700",
    website: "https://www.mywrc.org/",
    lat: 27.3300,
    lng: -82.5050,
    hours: "Mon-Thu: 9am-5pm, Fri: 9am-12pm",
    tags: ["Women's Support", "Mental Health", "Career"],
    services: ["Counseling", "Career Coaching", "Support Groups"]
  },
  {
    id: 51,
    name: "Children First",
    category: "Family Services",
    description: "The exclusive provider of Head Start and Early Head Start services for Sarasota County.",
    address: "1723 N Orange Ave, Sarasota, FL 34234",
    phone: "(941) 953-3877",
    website: "https://www.childrenfirst.net/",
    lat: 27.3480,
    lng: -82.5350,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Childcare", "Early Education", "Family Support"],
    services: ["Head Start", "Family Advocacy", "Health Screenings"]
  },
  {
    id: 52,
    name: "SunCoast Blood Centers",
    category: "Healthcare",
    description: "Independent community blood center providing a reliable supply of blood products to local hospitals.",
    address: "1760 Mound St, Sarasota, FL 34236",
    phone: "(866) 972-5663",
    website: "https://suncoastblood.org/",
    lat: 27.3260,
    lng: -82.5350,
    hours: "Check Website for Donor Hours",
    tags: ["Blood Donation", "Health", "Community"],
    services: ["Blood Donation", "Platelet Donation", "Health Check"]
  },
  {
    id: 53,
    name: "Sarasota Jungle Gardens",
    category: "Recreation",
    description: "One of Florida's oldest attractions, featuring tropical gardens and free-roaming flamingos.",
    address: "3701 Bay Shore Rd, Sarasota, FL 34234",
    phone: "(941) 355-5305",
    website: "https://sarasotajunglegardens.com/",
    lat: 27.3650,
    lng: -82.5550,
    hours: "Daily: 10am-4pm",
    tags: ["Attraction", "Animals", "Family"],
    services: ["Animal Shows", "Gardens", "Petting Zoo"]
  },
  {
    id: 54,
    name: "Big Cat Habitat",
    category: "Recreation",
    description: "A nonprofit sanctuary for big cats and other animals, founded by the Rosaire family.",
    address: "7101 Palmer Blvd, Sarasota, FL 34240",
    phone: "(941) 371-6377",
    website: "https://bigcathabitat.org/",
    lat: 27.3280,
    lng: -82.4200,
    hours: "Wed-Sun: 12pm-4pm",
    tags: ["Sanctuary", "Animals", "Conservation"],
    services: ["Animal Encounters", "Shows", "Education"]
  },
  {
    id: 55,
    name: "Gulf Gate Public Library",
    category: "Libraries",
    description: "A busy community library offering reading gardens, teen spaces, and diverse programming.",
    address: "7112 Curtiss Ave, Sarasota, FL 34231",
    phone: "(941) 861-1110",
    website: "https://www.scgov.net/government/departments/libraries/locations/gulf-gate-library",
    lat: 27.2625,
    lng: -82.5085,
    hours: "Mon-Wed: 10am-8pm, Thu-Sat: 10am-5pm",
    tags: ["Reading", "Education", "Community"],
    services: ["WiFi", "Meeting Rooms", "Tech Support"]
  },
  {
    id: 56,
    name: "Elsie Quirk Public Library",
    category: "Libraries",
    description: "Located in Englewood, providing access to books, technology, and community meeting spaces.",
    address: "100 W Venice Ave, Venice, FL 34285",
    phone: "(941) 861-1350",
    website: "https://www.scgov.net/government/departments/libraries/locations/elsie-quirk-library",
    lat: 27.1005,
    lng: -82.4495,
    hours: "Mon-Wed: 10am-8pm, Thu-Sat: 10am-5pm",
    tags: ["Public", "Books", "Internet"],
    services: ["Study Rooms", "Kids Programs", "Computers"]
  },
  {
    id: 57,
    name: "Osprey Public Library at Historic Spanish Point",
    category: "Libraries",
    description: "A unique library setting located within the Historic Spanish Point campus.",
    address: "337 N Tamiami Trail, Osprey, FL 34229",
    phone: "(941) 861-1330",
    website: "https://www.scgov.net/government/departments/libraries/locations/osprey-library",
    lat: 27.1985,
    lng: -82.4965,
    hours: "Tue-Fri: 10am-5pm, Sat: 10am-2pm",
    tags: ["History", "Quiet", "Culture"],
    services: ["Book Returns", "WiFi", "Local History"]
  },
  {
    id: 58,
    name: "Community Health Centers of Sarasota County",
    category: "Healthcare",
    description: "Federally Qualified Health Center providing affordable medical and dental care.",
    address: "2200 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 366-0134",
    website: "https://chc-sarasota.org",
    lat: 27.3364,
    lng: -82.5222,
    hours: "Mon-Fri: 7:30am-5:30pm",
    tags: ["Affordable", "Medical", "Dental"],
    services: ["Primary Care", "Pediatrics", "Dental Care"]
  },
  {
    id: 59,
    name: "Sarasota Medical Center",
    category: "Healthcare",
    description: "Walk-in urgent care and family practice serving the community for minor emergencies.",
    address: "4040 Cattlemen Rd, Sarasota, FL 34233",
    phone: "(941) 371-3337",
    website: "https://sarasotamedical.com",
    lat: 27.2985,
    lng: -82.459,
    hours: "Mon-Fri: 8am-5pm, Sat: 9am-1pm",
    tags: ["Urgent Care", "Medical", "Walk-in"],
    services: ["X-Ray", "Physicals", "Flu Shots"]
  },
  {
    id: 60,
    name: "Planned Parenthood - Sarasota Health Center",
    category: "Healthcare",
    description: "Provider of reproductive health care, education, and general health services.",
    address: "736 Central Ave, Sarasota, FL 34236",
    phone: "(941) 953-4060",
    website: "https://www.plannedparenthood.org",
    lat: 27.3458,
    lng: -82.5458,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Women's Health", "Screening", "Education"],
    services: ["Testing", "Wellness Exams", "Counseling"]
  },
  {
    id: 61,
    name: "Family Promise of South Sarasota County",
    category: "Shelters",
    description: "Organization helping children and their families in temporary crisis return to housing.",
    address: "215 Wexford Blvd, Venice, FL 34293",
    phone: "(941) 497-9881",
    website: "https://familypromisesarasota.org",
    lat: 27.085,
    lng: -82.4,
    hours: "Mon-Fri: 9am-4pm",
    tags: ["Families", "Housing", "Children"],
    services: ["Case Management", "Meals", "Shelter"]
  },
  {
    id: 62,
    name: "Salvation Army Sarasota Center of Hope",
    category: "Shelters",
    description: "Comprehensive social services agency offering emergency shelter and transitional housing.",
    address: "1400 10th St, Sarasota, FL 34236",
    phone: "(941) 954-4673",
    website: "https://salvationarmyflorida.org/sarasota",
    lat: 27.3465,
    lng: -82.5395,
    hours: "24 Hours",
    tags: ["Emergency", "Housing", "Recovery"],
    services: ["Emergency Shelter", "Soup Kitchen", "Rehab"]
  },
  {
    id: 63,
    name: "Catholic Charities Diocese of Venice",
    category: "Shelters",
    description: "Provides housing assistance, food pantries, and support for vulnerable populations.",
    address: "1000 Pinebrook Rd, Venice, FL 34285",
    phone: "(941) 488-5581",
    website: "https://catholiccharitiesdov.org",
    lat: 27.112,
    lng: -82.415,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Faith-based", "Support", "Housing"],
    services: ["Financial Aid", "Food", "Counseling"]
  },
  {
    id: 64,
    name: "Express Employment Professionals",
    category: "Job Services",
    description: "Staffing agency connecting job seekers with local employers for temporary and full-time work.",
    address: "6561 Palmer Park Cir, Sarasota, FL 34238",
    phone: "(941) 946-8600",
    website: "https://www.expresspros.com/sarasotafl",
    lat: 27.235,
    lng: -82.485,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Employment", "Staffing", "Careers"],
    services: ["Job Placement", "Recruiting", "Temp Work"]
  },
  {
    id: 65,
    name: "Suncoast Technical College",
    category: "Job Services",
    description: "Career and technical education center offering adult education and vocational training.",
    address: "4748 Beneva Rd, Sarasota, FL 34233",
    phone: "(941) 924-1365",
    website: "https://www.sarasotacountyschools.net/stc",
    lat: 27.2885,
    lng: -82.484,
    hours: "Mon-Fri: 8am-8pm",
    tags: ["Education", "Vocational", "Skills"],
    services: ["Certificate Programs", "GED", "Apprenticeships"]
  },
  {
    id: 66,
    name: "PeopleReady",
    category: "Job Services",
    description: "Staffing agency specializing in on-demand labor and temporary industrial jobs.",
    address: "4239 Bee Ridge Rd, Sarasota, FL 34233",
    phone: "(941) 377-5070",
    website: "https://www.peopleready.com",
    lat: 27.299,
    lng: -82.48,
    hours: "Mon-Fri: 6am-6pm",
    tags: ["Labor", "Temp", "Industrial"],
    services: ["Day Labor", "Construction", "Hospitality"]
  },
  {
    id: 67,
    name: "Urfer Family Park",
    category: "Parks",
    description: "Mixed-use park featuring nature trails, playgrounds, and picnic areas on 55 acres.",
    address: "4000 Honore Ave, Sarasota, FL 34233",
    phone: "(941) 861-5000",
    website: "https://www.scgov.net/parks",
    lat: 27.2988,
    lng: -82.4595,
    hours: "Daily: 6am-Sunset",
    tags: ["Nature", "Playground", "Trails"],
    services: ["Hiking", "Picnic Shelters", "Restrooms"]
  },
  {
    id: 68,
    name: "Rothenbach Park",
    category: "Parks",
    description: "Expansive park with paved trails for cycling and walking atop a repurposed landfill.",
    address: "8650 Bee Ridge Rd, Sarasota, FL 34241",
    phone: "(941) 861-5000",
    website: "https://www.scgov.net/parks",
    lat: 27.299,
    lng: -82.385,
    hours: "Daily: 6am-Sunset",
    tags: ["Cycling", "Walking", "Outdoors"],
    services: ["5 Mile Loop", "Restrooms", "Pavilion"]
  },
  {
    id: 69,
    name: "The Legacy Trail (Palmer Ranch)",
    category: "Parks",
    description: "Popular paved multi-use trail running through Sarasota County for biking and walking.",
    address: "8415 McIntosh Rd, Sarasota, FL 34238",
    phone: "(941) 861-5000",
    website: "https://www.friendsofthelegacytrail.org",
    lat: 27.234,
    lng: -82.484,
    hours: "Daily: 6am-Sunset",
    tags: ["Biking", "Running", "Health"],
    services: ["Paved Trail", "Parking", "Water Stations"]
  },
  {
    id: 70,
    name: "Sarasota Bradenton International Airport (SRQ)",
    category: "Transit",
    description: "Major international airport serving the Sarasota and Bradenton areas.",
    address: "6000 Airport Cir, Sarasota, FL 34243",
    phone: "(941) 359-2770",
    website: "https://srq-airport.com",
    lat: 27.3955,
    lng: -82.5544,
    hours: "24 Hours",
    tags: ["Travel", "Flights", "Transportation"],
    services: ["Flights", "Car Rental", "Parking"]
  },
  {
    id: 71,
    name: "Downtown Transfer Station",
    category: "Transit",
    description: "Central hub for Sarasota County transit buses with ticket office and waiting areas.",
    address: "156 N Lemon Ave, Sarasota, FL 34236",
    phone: "(941) 861-5000",
    website: "https://www.scgov.net/breeze",
    lat: 27.3355,
    lng: -82.541,
    hours: "Daily: 5am-10pm",
    tags: ["Bus", "Public Transit", "Downtown"],
    services: ["Bus Connections", "Tickets", "Shelter"]
  },
  {
    id: 72,
    name: "Church of the Palms Food Pantry",
    category: "Food Services",
    description: "Community food pantry providing grocery assistance to families in need.",
    address: "3224 Bee Ridge Rd, Sarasota, FL 34239",
    phone: "(941) 924-1323",
    website: "https://www.churchofthepalms.org",
    lat: 27.2985,
    lng: -82.505,
    hours: "Mon-Fri: Call for hours",
    tags: ["Food", "Charity", "Assistance"],
    services: ["Groceries", "Drive-thru", "Volunteering"]
  },
  {
    id: 73,
    name: "St. Barbara Greek Orthodox Church Pantry",
    category: "Food Services",
    description: "Outreach program managing a food pantry for local residents facing food insecurity.",
    address: "7671 N Lockwood Ridge Rd, Sarasota, FL 34243",
    phone: "(941) 355-2616",
    website: "https://stbarbarafldistrict.org",
    lat: 27.399,
    lng: -82.515,
    hours: "Monthly: Check Schedule",
    tags: ["Donations", "Community", "Food"],
    services: ["Food Distribution", "Support", "Outreach"]
  },
  {
    id: 74,
    name: "The Food Bank of Manatee",
    category: "Food Services",
    description: "Critical food distribution center serving Manatee County food pantries and agencies.",
    address: "811 23rd Ave E, Bradenton, FL 34208",
    phone: "(941) 747-3663",
    website: "https://foodbankofmanatee.org",
    lat: 27.475,
    lng: -82.55,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Hunger Relief", "Nonprofit", "Distribution"],
    services: ["Food Supply", "Disaster Relief", "Nutrition"]
  },
  {
    id: 75,
    name: "Girls Inc. of Sarasota County",
    category: "Youth Services",
    description: "Empowering girls to be strong, smart, and bold through research-based programming.",
    address: "201 S Tuttle Ave, Sarasota, FL 34237",
    phone: "(941) 366-6646",
    website: "https://girlsincsrq.org",
    lat: 27.33,
    lng: -82.518,
    hours: "Mon-Fri: 8am-6pm",
    tags: ["Girls", "Empowerment", "After-school"],
    services: ["Mentoring", "Education", "Summer Camp"]
  },
  {
    id: 76,
    name: "Sarasota County 4-H",
    category: "Youth Services",
    description: "Youth development program offering hands-on learning in agriculture, science, and citizenship.",
    address: "6700 Clark Rd, Sarasota, FL 34241",
    phone: "(941) 861-9900",
    website: "https://sfyl.ifas.ufl.edu/sarasota/4-h-youth-development",
    lat: 27.263,
    lng: -82.435,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Agriculture", "Leadership", "Clubs"],
    services: ["Projects", "Workshops", "Competitions"]
  },
  {
    id: 77,
    name: "Safe Children Coalition",
    category: "Youth Services",
    description: "Community based care agency providing foster care, adoption, and prevention services.",
    address: "1500 Independence Blvd, Sarasota, FL 34234",
    phone: "(941) 371-4799",
    website: "https://sccfl.org",
    lat: 27.36,
    lng: -82.54,
    hours: "Mon-Fri: 8:30am-5pm",
    tags: ["Child Welfare", "Safety", "Family"],
    services: ["Foster Care", "Adoption", "Case Management"]
  },
  {
    id: 78,
    name: "Neuro Challenge Foundation",
    category: "Senior Services",
    description: "Dedicated to improving the quality of life of people with Parkinson’s and their caregivers.",
    address: "5530 Bee Ridge Rd Suite 101, Sarasota, FL 34233",
    phone: "(941) 926-6413",
    website: "https://www.neurochallenge.org",
    lat: 27.298,
    lng: -82.46,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Parkinsons", "Support", "Health"],
    services: ["Education", "Support Groups", "Care Advising"]
  },
  {
    id: 79,
    name: "Parkinson Place",
    category: "Senior Services",
    description: "A multidisciplinary center offering free programs for members with Parkinson's disease.",
    address: "5969 Cattleridge Blvd, Sarasota, FL 34232",
    phone: "(941) 893-4188",
    website: "https://parkinsonplace.org",
    lat: 27.305,
    lng: -82.46,
    hours: "Mon-Fri: 9am-4pm",
    tags: ["Wellness", "Therapy", " Seniors"],
    services: ["Exercise Classes", "Voice Therapy", "Social"]
  },
  {
    id: 80,
    name: "ITN SunCoast",
    category: "Senior Services",
    description: "Dignified transportation service for seniors and adults with vision impairment.",
    address: "1704 McMullen Ln, Sarasota, FL 34236",
    phone: "(941) 364-7530",
    website: "https://itnsuncoast.org",
    lat: 27.33,
    lng: -82.53,
    hours: "Services available 24/7",
    tags: ["Transport", "Mobility", "Accessibility"],
    services: ["Rides", "Door-to-door", "Senior Travel"]
  },
  {
    id: 81,
    name: "Rotary Club of Sarasota",
    category: "Community Services",
    description: "Service organization of business and professional leaders facilitating humanitarian service.",
    address: "2 Marina Plaza, Sarasota, FL 34236",
    phone: "(941) 955-5858",
    website: "https://rotaryclubofsarasota.com",
    lat: 27.333,
    lng: -82.545,
    hours: "Meets Wednesdays",
    tags: ["Service", "Leadership", "Nonprofit"],
    services: ["Networking", "Volunteering", "Grants"]
  },
  {
    id: 82,
    name: "Junior League of Sarasota",
    category: "Community Services",
    description: "Women's organization committed to promoting voluntarism and improving the community.",
    address: "3300 S Tamiami Trail, Sarasota, FL 34239",
    phone: "(941) 953-5600",
    website: "https://www.jlsarasota.org",
    lat: 27.305,
    lng: -82.53,
    hours: "Mon-Fri: 9am-3pm",
    tags: ["Women", "Voluntarism", "Leadership"],
    services: ["Community Projects", "Training", "Advocacy"]
  },
  {
    id: 83,
    name: "Sarasota Garden Club",
    category: "Community Services",
    description: "Historic club dedicated to gardening, floral design, and environmental conservation.",
    address: "1131 Blvd of the Arts, Sarasota, FL 34236",
    phone: "(941) 955-0875",
    website: "https://www.sarasotagardenclub.org",
    lat: 27.34,
    lng: -82.548,
    hours: "Mon-Fri: 10am-4pm",
    tags: ["Nature", "Gardening", "Venue"],
    services: ["Gardens", "Event Space", "Workshops"]
  },
  {
    id: 84,
    name: "Ringling College of Art and Design",
    category: "Education",
    description: "Private college focused on art and design, offering degrees and continuing education.",
    address: "2700 N Tamiami Trail, Sarasota, FL 34234",
    phone: "(941) 351-5100",
    website: "https://www.ringling.edu",
    lat: 27.355,
    lng: -82.558,
    hours: "Mon-Fri: 8:30am-4:30pm",
    tags: ["Art", "College", "Design"],
    services: ["Degrees", "Continuing Ed", "Galleries"]
  },
  {
    id: 85,
    name: "USF Sarasota-Manatee",
    category: "Education",
    description: "Regional campus of the University of South Florida offering undergraduate and graduate degrees.",
    address: "8350 N Tamiami Trail, Sarasota, FL 34243",
    phone: "(941) 359-4200",
    website: "https://www.sarasotamanatee.usf.edu",
    lat: 27.392,
    lng: -82.56,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["University", "Degrees", "Research"],
    services: ["Higher Ed", "Student Services", "Library"]
  },
  {
    id: 86,
    name: "Gulfcoast Legal Services",
    category: "Legal Services",
    description: "Non-profit legal aid organization providing free assistance to vulnerable residents.",
    address: "1750 17th St, Sarasota, FL 34234",
    phone: "(941) 366-1746",
    website: "https://gulfcoastlegal.org",
    lat: 27.348,
    lng: -82.525,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Legal Aid", "Pro Bono", "Rights"],
    services: ["Civil Law", "Housing", "Immigration"]
  },
  {
    id: 87,
    name: "Family Law Self-Help Center",
    category: "Legal Services",
    description: "Provides procedural formatting assistance to self-represented litigants in family law cases.",
    address: "2002 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 861-7400",
    website: "https://www.sarasotaclerk.com",
    lat: 27.337,
    lng: -82.525,
    hours: "Mon-Fri: 8:30am-4:30pm",
    tags: ["Court", "Family Law", "Assistance"],
    services: ["Forms", "Notary", "Guidance"]
  }
];

// Featured resources for home page
const featuredResources = [
  resourcesDatabase.find(r => r.id === 1), // Selby Library
  resourcesDatabase.find(r => r.id === 9), // Siesta Beach
  resourcesDatabase.find(r => r.id === 4)  // Sarasota Memorial Hospital
].filter(Boolean);

// Categories for filtering
const categories = [
  "All Categories",
  "Libraries",
  "Healthcare",
  "Shelters",
  "Job Services",
  "Parks",
  "Transit",
  "Food Services",
  "Youth Services",
  "Senior Services",
  "Community Services",
  "Education",
  "Legal Services",
  "Support Services",
  "Family Services"
];
