// Sarasota Community Resources Database
const resourcesDatabase = [
  // REAL SARASOTA RESOURCES FROM USER-PROVIDED CSV BEGIN
  // (Insert the real, up-to-date Sarasota resources here, replacing all previous entries)
  // ...
  // REAL SARASOTA RESOURCES FROM USER-PROVIDED CSV END
  // Healthcare Clinics & Services
  {
    id: 49,
    name: "Sarasota Memorial Hospital",
    category: "Healthcare",
    description: "Full-service hospital with emergency care and specialized services",
    address: "1700 S Tamiami Trail, Sarasota, FL 34239",
    phone: "(941) 917-9000",
    website: "https://smh.com",
    lat: 27.3357,
    lng: -82.5339,
    hours: "24/7",
    tags: ["Hospital", "Emergency", "Healthcare"],
    services: ["Emergency Room", "Surgery", "Radiology", "Cardiology"]
  },
  {
    id: 50,
    name: "Doctors Hospital of Sarasota",
    category: "Healthcare",
    description: "Community hospital offering surgical and medical services",
    address: "5731 Bee Ridge Rd, Sarasota, FL 34233",
    phone: "(941) 342-1100",
    website: "https://doctorshospital.com",
    lat: 27.2819,
    lng: -82.4781,
    hours: "24/7",
    tags: ["Hospital", "Medical", "Surgical"],
    services: ["Surgery", "Maternity", "Orthopedics"]
  },
  {
    id: 51,
    name: "Community Health Centers of Florida",
    category: "Healthcare",
    description: "Federally qualified health center providing primary care",
    address: "2415 Proctor St, Sarasota, FL 34234",
    phone: "(941) 955-7541",
    website: "https://chcfl.org",
    lat: 27.3412,
    lng: -82.5378,
    hours: "Mon-Fri: 7:30am-5pm",
    tags: ["Primary Care", "Clinic", "Affordable"],
    services: ["Medical Care", "Dental", "Behavioral Health"]
  },
  {
    id: 52,
    name: "Planned Parenthood of Southwest Florida",
    category: "Healthcare",
    description: "Women's reproductive health services",
    address: "2173 Commercial Ct, Sarasota, FL 34234",
    phone: "(941) 953-4060",
    website: "https://plannedparenthood.org",
    lat: 27.3456,
    lng: -82.5401,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Women's Health", "Reproductive", "Clinic"],
    services: ["Family Planning", "Preventive Care", "Testing"]
  },
  {
    id: 53,
    name: "Sarasota County Health Department",
    category: "Healthcare",
    description: "Public health services including immunizations and disease prevention",
    address: "2200 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 861-4904",
    website: "https://scgov.net",
    lat: 27.3524,
    lng: -82.5334,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Public Health", "Immunizations", "Prevention"],
    services: ["Vaccines", "Testing", "Health Education"]
  },
  // Parks & Recreation
  {
    id: 54,
    name: "Myakka River State Park",
    category: "Parks",
    description: "Large state park with hiking, camping, and wildlife viewing",
    address: "13207 SR-72, Sarasota, FL 34241",
    phone: "(941) 361-6511",
    website: "https://floridastateparks.org",
    lat: 27.1834,
    lng: -82.2411,
    hours: "8am-sunset",
    tags: ["Camping", "Hiking", "Wildlife"],
    services: ["Trails", "Canoe Rentals", "Picnic Areas"]
  },
  {
    id: 55,
    name: "Lido Beach",
    category: "Parks",
    description: "Popular beach with white sand and family amenities",
    address: "2000 Ben Franklin Dr, Sarasota, FL 34236",
    phone: "(941) 316-1172",
    website: "https://scgov.net",
    lat: 27.3402,
    lng: -82.5706,
    hours: "Sun-Thurs: 8am-10pm, Fri-Sat: 8am-11pm",
    tags: ["Beach", "Recreation", "Family"],
    services: ["Parking", "Facilities", "Lifeguard"]
  },
  {
    id: 56,
    name: "South Lido Park",
    category: "Parks",
    description: "Beach park with nature trails and observation tower",
    address: "2000 S Ben Franklin Dr, Sarasota, FL 34236",
    phone: "(941) 316-1172",
    website: "https://scgov.net",
    lat: 27.3295,
    lng: -82.5811,
    hours: "Sunrise-sunset",
    tags: ["Beach", "Nature", "Walking"],
    services: ["Trails", "Picnic Areas", "Restrooms"]
  },
  {
    id: 57,
    name: "Ringling Nature Preserve",
    category: "Parks",
    description: "Scenic preserve with walking trails and wildlife observation",
    address: "3780 Ringling Blvd, Sarasota, FL 34231",
    phone: "(941) 359-3700",
    website: "https://ringling.org",
    lat: 27.3612,
    lng: -82.5201,
    hours: "9am-5pm",
    tags: ["Nature", "Walking", "Education"],
    services: ["Trails", "Guided Tours", "Programs"]
  },
  {
    id: 58,
    name: "Sarasota Parks & Recreation",
    category: "Parks",
    description: "Municipal parks and recreation programs",
    address: "2300 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 966-2200",
    website: "https://scgov.net",
    lat: 27.3524,
    lng: -82.5334,
    hours: "Mon-Fri: 8:30am-5pm",
    tags: ["Recreation", "Programs", "Parks"],
    services: ["Sports", "Classes", "Community Events"]
  },
  // Food Services & Pantries
  {
    id: 59,
    name: "Feeding Tampa Bay Sarasota",
    category: "Food Services",
    description: "Food bank serving food-insecure families in Sarasota",
    address: "5610 Cattlemen Rd, Sarasota, FL 34232",
    phone: "(941) 254-2555",
    website: "https://feedingtampabay.org",
    lat: 27.2845,
    lng: -82.4762,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Food Bank", "Assistance", "Emergency"],
    services: ["Food Distribution", "Partner Agencies", "Assistance"]
  },
  {
    id: 60,
    name: "Community Food Bank of Sarasota",
    category: "Food Services",
    description: "Emergency food assistance and nutrition programs",
    address: "6918 Clark Rd, Sarasota, FL 34233",
    phone: "(941) 378-6000",
    website: "https://communityfoodbank.org",
    lat: 27.2722,
    lng: -82.4890,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Food Assistance", "Nutrition", "Emergency"],
    services: ["Food Pantry", "Soup Kitchen", "Programs"]
  },
  {
    id: 61,
    name: "Harry Chapin Food Bank Distribution",
    category: "Food Services",
    description: "Weekly food distribution for eligible families",
    address: "2230 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 747-8879",
    website: "https://harrychapinfoodbank.org",
    lat: 27.3524,
    lng: -82.5334,
    hours: "Varies",
    tags: ["Food Distribution", "Weekly", "Emergency"],
    services: ["Food Pantry", "Nutrition", "Support"]
  },
  {
    id: 62,
    name: "Meals on Wheels Sarasota",
    category: "Food Services",
    description: "Meal delivery for seniors and homebound individuals",
    address: "1925 Ringling Blvd, Sarasota, FL 34236",
    phone: "(941) 954-4989",
    website: "https://mealsonwheels.org",
    lat: 27.3495,
    lng: -82.5312,
    hours: "Mon-Fri: 8am-4pm",
    tags: ["Seniors", "Meals", "Delivery"],
    services: ["Hot Meals", "Wellness Check", "Nutrition"]
  },
  // Education & Tutoring
  {
    id: 63,
    name: "Sarasota County Public Schools",
    category: "Education",
    description: "Public school system serving Sarasota County",
    address: "1960 Landings Blvd, Sarasota, FL 34231",
    phone: "(941) 927-9000",
    website: "https://sarasotacountyschools.net",
    lat: 27.3456,
    lng: -82.5289,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["K-12 Education", "Public Schools", "Administration"],
    services: ["Education", "Programs", "Information"]
  },
  {
    id: 64,
    name: "Santa Fe Teaching Laboratory",
    category: "Education",
    description: "Tutoring and academic support for students",
    address: "1223 N Tamiami Trail, Sarasota, FL 34236",
    phone: "(941) 951-0588",
    website: "https://santafelabs.com",
    lat: 27.3456,
    lng: -82.5201,
    hours: "Mon-Fri: 3pm-8pm",
    tags: ["Tutoring", "Academic", "Support"],
    services: ["SAT Prep", "Math Tutoring", "Test Prep"]
  },
  {
    id: 65,
    name: "New College of Florida",
    category: "Education",
    description: "Public honors college with liberal arts focus",
    address: "5700 N Tamiami Trail, Sarasota, FL 34243",
    phone: "(941) 487-5000",
    website: "https://ncf.edu",
    lat: 27.3789,
    lng: -82.5101,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["College", "Education", "Higher Learning"],
    services: ["Degree Programs", "Events", "Community"]
  },
  {
    id: 66,
    name: "Ringling College of Art and Design",
    category: "Education",
    description: "Private arts college with creative programs",
    address: "2700 N Tamiami Trail, Sarasota, FL 34234",
    phone: "(941) 351-5100",
    website: "https://ringling.edu",
    lat: 27.3645,
    lng: -82.5145,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Art Education", "Design", "College"],
    services: ["Degrees", "Workshops", "Facilities"]
  },
  // Job Services & Employment
  {
    id: 67,
    name: "CareerSource Sarasota",
    category: "Job Services",
    description: "Workforce development and job training programs",
    address: "1801 9th St, Sarasota, FL 34236",
    phone: "(941) 361-6000",
    website: "https://careersourcesarasota.com",
    lat: 27.3345,
    lng: -82.5378,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Jobs", "Training", "Employment"],
    services: ["Job Search", "Training", "Resume Help"]
  },
  {
    id: 68,
    name: "Sarasota Economic Development Corporation",
    category: "Job Services",
    description: "Business development and employment opportunities",
    address: "1945 N Fruitville Rd, Sarasota, FL 34236",
    phone: "(941) 957-1877",
    website: "https://sedcorp.org",
    lat: 27.3587,
    lng: -82.5267,
    hours: "Mon-Fri: 8:30am-5pm",
    tags: ["Business", "Employment", "Development"],
    services: ["Business Info", "Connections", "Resources"]
  },
  {
    id: 69,
    name: "Florida Department of Economic Opportunity",
    category: "Job Services",
    description: "State job assistance and unemployment services",
    address: "2748 Fruitville Rd, Sarasota, FL 34237",
    phone: "(941) 361-6011",
    website: "https://floridajobs.org",
    lat: 27.3456,
    lng: -82.5234,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Jobs", "Unemployment", "State Services"],
    services: ["Job Board", "Benefits", "Training"]
  },
  // Senior Services
  {
    id: 70,
    name: "Area Agency on Aging Sarasota",
    category: "Senior Services",
    description: "Senior programs and services coordination",
    address: "1553 1st St, Sarasota, FL 34236",
    phone: "(941) 951-1122",
    website: "https://aaasarasota.org",
    lat: 27.3412,
    lng: -82.5345,
    hours: "Mon-Fri: 8am-4:30pm",
    tags: ["Seniors", "Programs", "Aging"],
    services: ["Case Management", "Programs", "Resources"]
  },
  {
    id: 71,
    name: "Brookdale Sarasota Senior Living",
    category: "Senior Services",
    description: "Senior community with independent living",
    address: "5151 Bahia Vista St, Sarasota, FL 34232",
    phone: "(941) 922-1112",
    website: "https://brookdale.com",
    lat: 27.3345,
    lng: -82.4956,
    hours: "Daily",
    tags: ["Senior Living", "Housing", "Community"],
    services: ["Independent Living", "Dining", "Activities"]
  },
  {
    id: 72,
    name: "Senior Friendship Centers",
    category: "Senior Services",
    description: "Social and recreational programs for seniors",
    address: "1888 Brother Geenen Way, Sarasota, FL 34231",
    phone: "(941) 955-5540",
    website: "https://seniorfriendshipcenters.org",
    lat: 27.3401,
    lng: -82.5234,
    hours: "Mon-Fri: 8:30am-4:30pm",
    tags: ["Seniors", "Recreation", "Social"],
    services: ["Programs", "Classes", "Events"]
  },
  // Youth Services
  {
    id: 73,
    name: "Boys & Girls Clubs of Sarasota",
    category: "Youth Services",
    description: "Youth development and after-school programs",
    address: "1212 N Tamiami Trail, Sarasota, FL 34236",
    phone: "(941) 365-0310",
    website: "https://bgcsarasota.org",
    lat: 27.3467,
    lng: -82.5234,
    hours: "Mon-Fri: 2pm-8pm",
    tags: ["Youth", "Programs", "After School"],
    services: ["Programs", "Tutoring", "Recreation"]
  },
  {
    id: 74,
    name: "Sarasota Youth Development Zone",
    category: "Youth Services",
    description: "Youth mentorship and development programs",
    address: "1435 Lenox Ave, Sarasota, FL 34234",
    phone: "(941) 486-4500",
    website: "https://sydz.org",
    lat: 27.3367,
    lng: -82.5456,
    hours: "Mon-Fri: 3pm-8pm",
    tags: ["Youth", "Mentorship", "Development"],
    services: ["Mentoring", "Programs", "Support"]
  },
  {
    id: 75,
    name: "Selby Public Library Teen Programs",
    category: "Youth Services",
    description: "Library programs for teenagers",
    address: "1331 1st St, Sarasota, FL 34236",
    phone: "(941) 861-1110",
    website: "https://sarasotalibraries.org",
    lat: 27.3412,
    lng: -82.5334,
    hours: "Mon-Sat: 10am-6pm",
    tags: ["Teen", "Library", "Programs"],
    services: ["Coding", "Gaming", "Classes"]
  },
  // Community Services & Support
  {
    id: 76,
    name: "Sarasota Community Foundation",
    category: "Community Services",
    description: "Philanthropic organization supporting community programs",
    address: "2635 Fruitville Rd, Sarasota, FL 34237",
    phone: "(941) 955-0800",
    website: "https://sarasotafoundation.org",
    lat: 27.3456,
    lng: -82.5267,
    hours: "Mon-Fri: 8:30am-5pm",
    tags: ["Foundation", "Grants", "Community"],
    services: ["Grants", "Philanthropy", "Events"]
  },
  {
    id: 77,
    name: "2-1-1 Sarasota",
    category: "Community Services",
    description: "Information and referral service for human services",
    address: "2200 Ringling Blvd, Sarasota, FL 34237",
    phone: "2-1-1",
    website: "https://211.org",
    lat: 27.3524,
    lng: -82.5334,
    hours: "24/7",
    tags: ["Information", "Referral", "Help"],
    services: ["Information", "Referral", "Crisis Support"]
  },
  {
    id: 78,
    name: "Sarasota County Emergency Management",
    category: "Community Services",
    description: "Disaster preparedness and emergency response",
    address: "1111 3rd Ave W, Bradenton, FL 34205",
    phone: "(941) 747-3011",
    website: "https://scgov.net",
    lat: 27.4892,
    lng: -82.5156,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Emergency", "Preparedness", "Safety"],
    services: ["Planning", "Response", "Information"]
  },
  // Legal Services
  {
    id: 79,
    name: "Community Legal Services",
    category: "Legal Services",
    description: "Free legal assistance for low-income residents",
    address: "1971 Ringling Blvd, Sarasota, FL 34236",
    phone: "(941) 954-0313",
    website: "https://legalaid.org",
    lat: 27.3495,
    lng: -82.5312,
    hours: "Mon-Fri: 8:30am-5pm",
    tags: ["Legal", "Assistance", "Free"],
    services: ["Advice", "Representation", "Advocacy"]
  },
  {
    id: 80,
    name: "Florida Bar Lawyer Referral Service",
    category: "Legal Services",
    description: "Attorney referrals and legal information",
    address: "651 E Jefferson St, Tallahassee, FL 32399",
    phone: "(800) 342-8060",
    website: "https://floridabar.org",
    lat: 30.4383,
    lng: -84.2807,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Legal", "Referral", "Attorney"],
    services: ["Referrals", "Information", "Assistance"]
  },
  // Support Services & Mental Health
  {
    id: 81,
    name: "Crisis Center North Sarasota",
    category: "Support Services",
    description: "24/7 crisis counseling and suicide prevention",
    address: "2395 Lime Ave, Venice, FL 34285",
    phone: "(941) 423-1477",
    website: "https://crisiscenterscc.org",
    lat: 27.1045,
    lng: -82.4578,
    hours: "24/7",
    tags: ["Crisis", "Mental Health", "Emergency"],
    services: ["Hotline", "Counseling", "Support"]
  },
  {
    id: 82,
    name: "National Alliance on Mental Illness Sarasota",
    category: "Support Services",
    description: "Mental health support and education",
    address: "1192 S Euclid Ave, Sarasota, FL 34236",
    phone: "(941) 927-8900",
    website: "https://namiscc.org",
    lat: 27.3234,
    lng: -82.5401,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Mental Health", "Support", "Education"],
    services: ["Support Groups", "Classes", "Resources"]
  },
  {
    id: 83,
    name: "Sarasota Mental Health Center",
    category: "Support Services",
    description: "Comprehensive mental health and substance abuse services",
    address: "1550 S Osprey Ave, Sarasota, FL 34239",
    phone: "(941) 927-9800",
    website: "https://smhc.org",
    lat: 27.3234,
    lng: -82.5367,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Mental Health", "Therapy", "Substance Abuse"],
    services: ["Counseling", "Treatment", "Crisis Care"]
  },
  {
    id: 84,
    name: "Alcoholics Anonymous Sarasota",
    category: "Support Services",
    description: "12-step recovery program for alcohol addiction",
    address: "Multiple Locations",
    phone: "(941) 953-5815",
    website: "https://aasarasota.org",
    lat: 27.3356,
    lng: -82.5306,
    hours: "Daily",
    tags: ["Addiction", "Recovery", "Support"],
    services: ["Meetings", "Sponsorship", "Support"]
  },
  {
    id: 85,
    name: "Narcotics Anonymous Sarasota",
    category: "Support Services",
    description: "12-step program for drug addiction recovery",
    address: "Multiple Locations",
    phone: "(941) 954-1500",
    website: "https://nasarasota.org",
    lat: 27.3356,
    lng: -82.5306,
    hours: "Daily",
    tags: ["Addiction", "Recovery", "Support"],
    services: ["Meetings", "Support", "Community"]
  },
  // Transportation
  {
    id: 86,
    name: "Sarasota County Transit (SCAT)",
    category: "Transit",
    description: "Public bus transportation throughout Sarasota County",
    address: "1117 S Euclid Ave, Sarasota, FL 34236",
    phone: "(941) 861-1234",
    website: "https://scgov.net/scat",
    lat: 27.3234,
    lng: -82.5401,
    hours: "Mon-Sun: 5:30am-11pm",
    tags: ["Transportation", "Bus", "Public Transit"],
    services: ["Bus Service", "Routes", "Passes"]
  },
  {
    id: 87,
    name: "Sarasota Taxi Service Association",
    category: "Transit",
    description: "Licensed taxi service",
    address: "1200 S Osprey Ave, Sarasota, FL 34239",
    phone: "(941) 316-1234",
    website: "https://sarasotataxi.com",
    lat: 27.3234,
    lng: -82.5367,
    hours: "24/7",
    tags: ["Taxi", "Transportation", "Local"],
    services: ["Taxi Service", "Airport Transfer", "Local"]
  },
  {
    id: 88,
    name: "Uber & Lyft Sarasota",
    category: "Transit",
    description: "Ride-sharing services",
    address: "Available via App",
    phone: "(855) 638-3847",
    website: "https://uber.com",
    lat: 27.3356,
    lng: -82.5306,
    hours: "24/7",
    tags: ["Rideshare", "Transportation", "Technology"],
    services: ["Rides", "Delivery", "Premium"]
  },
  {
    id: 89,
    name: "Paratransit Services for Disabled",
    category: "Transit",
    description: "ADA-compliant transportation for disabled individuals",
    address: "1117 S Euclid Ave, Sarasota, FL 34236",
    phone: "(941) 861-1234",
    website: "https://scgov.net/scat",
    lat: 27.3234,
    lng: -82.5401,
    hours: "Mon-Sun: 5:30am-11pm",
    tags: ["Transportation", "Disabled", "ADA"],
    services: ["Door-to-Door", "Accessibility", "Assistance"]
  },
  // More Healthcare
  {
    id: 90,
    name: "Urgent Care Express",
    category: "Healthcare",
    description: "Walk-in urgent care clinic",
    address: "8234 S Tamiami Trail, Sarasota, FL 34238",
    phone: "(941) 923-5900",
    website: "https://urgentcareexpress.com",
    lat: 27.3012,
    lng: -82.5289,
    hours: "Mon-Fri: 8am-9pm, Sat-Sun: 9am-7pm",
    tags: ["Urgent Care", "Medical", "Walk-In"],
    services: ["Minor Injuries", "Illness", "Testing"]
  },
  {
    id: 91,
    name: "Sarasota Dermatology Center",
    category: "Healthcare",
    description: "Dermatological services and skin care",
    address: "3131 S Tamiami Trail, Sarasota, FL 34239",
    phone: "(941) 953-4860",
    website: "https://sarasotaderm.com",
    lat: 27.3256,
    lng: -82.5334,
    hours: "Mon-Fri: 8:30am-5pm",
    tags: ["Dermatology", "Skin Care", "Medical"],
    services: ["Skin Treatment", "Cosmetic", "Laser"]
  },
  {
    id: 92,
    name: "Sarasota Vision Center",
    category: "Healthcare",
    description: "Optometry and eye care services",
    address: "5401 S Tamiami Trail, Sarasota, FL 34231",
    phone: "(941) 952-8800",
    website: "https://sarasotavision.com",
    lat: 27.2945,
    lng: -82.5367,
    hours: "Mon-Fri: 9am-5:30pm, Sat: 9am-2pm",
    tags: ["Eye Care", "Optometry", "Vision"],
    services: ["Eye Exams", "Glasses", "Contacts"]
  },
  {
    id: 93,
    name: "Sarasota Dental Associates",
    category: "Healthcare",
    description: "General and cosmetic dental services",
    address: "4501 Fruitville Rd, Sarasota, FL 34237",
    phone: "(941) 353-8988",
    website: "https://sarasotadental.com",
    lat: 27.3467,
    lng: -82.5123,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Dental", "Medical", "Cosmetic"],
    services: ["Cleanings", "Fillings", "Cosmetic"]
  },
  {
    id: 94,
    name: "Rehabilitation Services of Sarasota",
    category: "Healthcare",
    description: "Physical therapy and rehabilitation",
    address: "3600 Webber St, Sarasota, FL 34237",
    phone: "(941) 952-8888",
    website: "https://rehab-sarasota.com",
    lat: 27.3367,
    lng: -82.5378,
    hours: "Mon-Fri: 7am-6pm, Sat: 8am-12pm",
    tags: ["Physical Therapy", "Rehabilitation", "Medical"],
    services: ["PT/OT", "Injury Recovery", "Wellness"]
  },
  // Recreation & Arts
  {
    id: 95,
    name: "Sarasota Opera",
    category: "Recreation",
    description: "Professional opera company and performances",
    address: "61 N Pineapple Ave, Sarasota, FL 34236",
    phone: "(941) 953-7030",
    website: "https://sarasotaopera.org",
    lat: 27.3345,
    lng: -82.5312,
    hours: "Varies",
    tags: ["Arts", "Performance", "Culture"],
    services: ["Opera Productions", "Classes", "Events"]
  },
  {
    id: 96,
    name: "Ringling Museum",
    category: "Recreation",
    description: "Art museum with extensive collections",
    address: "5401 Bay Shore Rd, Sarasota, FL 34243",
    phone: "(941) 359-3700",
    website: "https://ringling.org",
    lat: 27.3612,
    lng: -82.5201,
    hours: "Tue-Sun: 10am-5:30pm",
    tags: ["Museum", "Art", "Culture"],
    services: ["Exhibitions", "Tours", "Events"]
  },
  {
    id: 97,
    name: "Sarasota Ballet",
    category: "Recreation",
    description: "Professional ballet company",
    address: "Sarasota Opera House, 61 N Pineapple Ave, Sarasota, FL 34236",
    phone: "(941) 359-0099",
    website: "https://sarasotaballet.org",
    lat: 27.3345,
    lng: -82.5312,
    hours: "Varies",
    tags: ["Ballet", "Performance", "Arts"],
    services: ["Performances", "Classes", "Events"]
  },
  {
    id: 98,
    name: "Florida Studio Theatre",
    category: "Recreation",
    description: "Regional professional theatre company",
    address: "1241 N Palm Ave, Sarasota, FL 34236",
    phone: "(941) 366-9000",
    website: "https://floridastudiotheatre.org",
    lat: 27.3445,
    lng: -82.5234,
    hours: "Varies",
    tags: ["Theatre", "Performance", "Arts"],
    services: ["Productions", "Classes", "Events"]
  },
  {
    id: 99,
    name: "Asolo Repertory Theatre",
    category: "Recreation",
    description: "Tony Award-winning theatre company",
    address: "5555 N Tamiami Trail, Sarasota, FL 34243",
    phone: "(941) 351-8000",
    website: "https://asolorep.org",
    lat: 27.3701,
    lng: -82.5145,
    hours: "Varies",
    tags: ["Theatre", "Professional", "Arts"],
    services: ["Productions", "Classes", "Events"]
  },
  // Business & Professional
  {
    id: 100,
    name: "Greater Sarasota Chamber of Commerce",
    category: "Community Services",
    description: "Business and economic development organization",
    address: "1945 N Fruitville Rd, Sarasota, FL 34236",
    phone: "(941) 955-8187",
    website: "https://sarasotachamber.com",
    lat: 27.3587,
    lng: -82.5267,
    hours: "Mon-Fri: 8:30am-5pm",
    tags: ["Business", "Chamber", "Network"],
    services: ["Networking", "Events", "Resources"]
  },
  {
    id: 101,
    name: "Women in Business Sarasota",
    category: "Community Services",
    description: "Women entrepreneurship and professional development",
    address: "1945 N Fruitville Rd, Sarasota, FL 34236",
    phone: "(941) 953-5895",
    website: "https://womeninbusiness-sarasota.org",
    lat: 27.3587,
    lng: -82.5267,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Women", "Business", "Entrepreneurship"],
    services: ["Mentoring", "Networking", "Training"]
  },
  {
    id: 102,
    name: "SCORE Sarasota",
    category: "Job Services",
    description: "Small business mentoring and advice",
    address: "1945 N Fruitville Rd, Sarasota, FL 34236",
    phone: "(941) 955-1029",
    website: "https://score.org",
    lat: 27.3587,
    lng: -82.5267,
    hours: "Mon-Fri: 10am-4pm",
    tags: ["Business", "Mentoring", "Startup"],
    services: ["Mentoring", "Workshops", "Planning"]
  },
  // More Parks & Recreation
  {
    id: 103,
    name: "Sarasota Jungle Gardens",
    category: "Parks",
    description: "Botanical gardens with nature trails",
    address: "3701 S Tamiami Trail, Sarasota, FL 34239",
    phone: "(941) 355-5305",
    website: "https://sarasotajunglegardens.org",
    lat: 27.3167,
    lng: -82.5334,
    hours: "10am-5pm daily",
    tags: ["Gardens", "Nature", "Recreation"],
    services: ["Trails", "Tours", "Classes"]
  },
  {
    id: 104,
    name: "Marie Selby Botanical Gardens",
    category: "Parks",
    description: "Orchid gardens and plant collections",
    address: "811 S Palm Ave, Sarasota, FL 34236",
    phone: "(941) 366-5731",
    website: "https://selby.org",
    lat: 27.3245,
    lng: -82.5334,
    hours: "10am-5pm daily",
    tags: ["Botanical", "Gardens", "Plants"],
    services: ["Tours", "Classes", "Events"]
  },
  {
    id: 105,
    name: "Siesta Key Beach Pavilion",
    category: "Parks",
    description: "Beach recreation and water sports facilities",
    address: "948 Beach Rd, Sarasota, FL 34242",
    phone: "(941) 346-3771",
    website: "https://scgov.net",
    lat: 27.2867,
    lng: -82.5834,
    hours: "Sunrise-sunset",
    tags: ["Beach", "Water Sports", "Recreation"],
    services: ["Rentals", "Lessons", "Facilities"]
  },
  // Additional Support Services
  {
    id: 106,
    name: "Sarasota Homeless Services",
    category: "Shelters",
    description: "Emergency shelter and supportive services",
    address: "1905 S Osprey Ave, Sarasota, FL 34239",
    phone: "(941) 365-1881",
    website: "https://sarasotaworks.org",
    lat: 27.3156,
    lng: -82.5367,
    hours: "24/7",
    tags: ["Shelter", "Homeless", "Emergency"],
    services: ["Emergency Shelter", "Case Management", "Programs"]
  },
  {
    id: 107,
    name: "Sarasota Domestic Violence Services",
    category: "Support Services",
    description: "Support for domestic violence survivors",
    address: "Confidential Location",
    phone: "(941) 365-1881",
    website: "https://domesticviolence-sarasota.org",
    lat: 27.3356,
    lng: -82.5306,
    hours: "24/7",
    tags: ["Domestic Violence", "Support", "Emergency"],
    services: ["Shelter", "Counseling", "Hotline"]
  },
  {
    id: 108,
    name: "Sexual Assault Services",
    category: "Support Services",
    description: "Support for sexual assault survivors",
    address: "Confidential Location",
    phone: "(941) 451-4SAY",
    website: "https://sexualassault-sarasota.org",
    lat: 27.3356,
    lng: -82.5306,
    hours: "24/7",
    tags: ["Sexual Assault", "Support", "Crisis"],
    services: ["Hotline", "Counseling", "Advocacy"]
  },
  {
    id: 109,
    name: "Sarasota Veterans Services",
    category: "Support Services",
    description: "Support and services for military veterans",
    address: "1555 E Palm Ave, Sarasota, FL 34236",
    phone: "(941) 951-5801",
    website: "https://scgov.net/veterans",
    lat: 27.3345,
    lng: -82.5201,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Veterans", "Military", "Support"],
    services: ["Benefits", "Programs", "Employment"]
  },
  {
    id: 110,
    name: "American Red Cross Sarasota",
    category: "Community Services",
    description: "Disaster relief and community services",
    address: "6001 S Tamiami Trail, Sarasota, FL 34231",
    phone: "(941) 953-5815",
    website: "https://redcross.org",
    lat: 27.2834,
    lng: -82.5378,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Disaster Relief", "Blood Drive", "Training"],
    services: ["Disaster Relief", "Blood", "First Aid Training"]
  },
  // Additional Parks
  {
    id: 111,
    name: "Oscar Scherer State Park",
    category: "Parks",
    description: "State park with wildlife viewing and trails",
    address: "1843 S Clark Rd, Osprey, FL 34229",
    phone: "(941) 483-5956",
    website: "https://floridastateparks.org",
    lat: 27.1567,
    lng: -82.4712,
    hours: "8am-sunset",
    tags: ["State Park", "Wildlife", "Trails"],
    services: ["Trails", "Bird Watching", "Picnic"]
  },
  {
    id: 112,
    name: "Caspersen Beach",
    category: "Parks",
    description: "Quiet beach with natural vegetation",
    address: "4800 Manasota Key Rd, Venice, FL 34293",
    phone: "(941) 486-2626",
    website: "https://scgov.net",
    lat: 26.9867,
    lng: -82.5734,
    hours: "Sunrise-sunset",
    tags: ["Beach", "Nature", "Quiet"],
    services: ["Parking", "Beach Access", "Facilities"]
  },
  {
    id: 113,
    name: "Turtle Beach",
    category: "Parks",
    description: "Beach park with fishing pier",
    address: "8862 Midnight Pass Rd, Siesta Key, Sarasota, FL 34242",
    phone: "(941) 316-1172",
    website: "https://scgov.net",
    lat: 27.2601,
    lng: -82.5845,
    hours: "Sunrise-sunset",
    tags: ["Beach", "Fishing", "Recreation"],
    services: ["Fishing Pier", "Parking", "Facilities"]
  },
  {
    id: 114,
    name: "Nokomis Beach",
    category: "Parks",
    description: "Family-friendly beach with amenities",
    address: "101 Albee Farm Rd, Nokomis, FL 34275",
    phone: "(941) 486-2626",
    website: "https://scgov.net",
    lat: 27.0856,
    lng: -82.5823,
    hours: "Sunrise-sunset",
    tags: ["Beach", "Family", "Amenities"],
    services: ["Lifeguard", "Parking", "Pavilion"]
  },
  // Additional Food Services
  {
    id: 115,
    name: "Sarasota County Extension Food Programs",
    category: "Food Services",
    description: "Nutrition education and food assistance programs",
    address: "2200 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 861-4904",
    website: "https://scgov.net",
    lat: 27.3524,
    lng: -82.5334,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Nutrition", "Education", "Assistance"],
    services: ["Nutrition Classes", "Food Assistance", "Education"]
  },
  {
    id: 116,
    name: "Sarasota Farmers Market",
    category: "Food Services",
    description: "Local farmers market with fresh produce",
    address: "1101 N Tamiami Trail, Sarasota, FL 34236",
    phone: "(941) 309-6646",
    website: "https://sarasotafarmersmarket.org",
    lat: 27.3556,
    lng: -82.5156,
    hours: "Sat: 8am-1pm",
    tags: ["Farmers Market", "Local", "Fresh Produce"],
    services: ["Fresh Produce", "Local Vendors", "Community"]
  },
  // Additional Education
  {
    id: 117,
    name: "Sarasota Adult Education",
    category: "Education",
    description: "Adult education and GED programs",
    address: "1960 Landings Blvd, Sarasota, FL 34231",
    phone: "(941) 927-9000",
    website: "https://sarasotaschools.net",
    lat: 27.3456,
    lng: -82.5289,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Adult Education", "GED", "Training"],
    services: ["GED Prep", "ESL", "Adult Classes"]
  },
  {
    id: 118,
    name: "Sarasota Public Library - South Branch",
    category: "Libraries",
    description: "South branch of public library system",
    address: "6106 S Tamiami Trail, Sarasota, FL 34231",
    phone: "(941) 861-1110",
    website: "https://sarasotalibraries.org",
    lat: 27.2834,
    lng: -82.5378,
    hours: "Mon-Fri: 10am-6pm, Sat: 10am-5pm",
    tags: ["Library", "Computers", "Programs"],
    services: ["Books", "Computers", "Programs"]
  },
  {
    id: 119,
    name: "Venice Public Library",
    category: "Libraries",
    description: "Public library in Venice",
    address: "300 S Nokomis Ave, Venice, FL 34285",
    phone: "(941) 861-1110",
    website: "https://sarasotalibraries.org",
    lat: 27.0967,
    lng: -82.4645,
    hours: "Mon-Fri: 10am-6pm, Sat: 10am-5pm",
    tags: ["Library", "Community", "Services"],
    services: ["Books", "Computers", "Events"]
  },
  // Additional Healthcare
  {
    id: 120,
    name: "Pharmacy Services at Walgreens",
    category: "Healthcare",
    description: "Prescription medications and health services",
    address: "Multiple Locations in Sarasota",
    phone: "(941) 951-5555",
    website: "https://walgreens.com",
    lat: 27.3356,
    lng: -82.5306,
    hours: "Varies by location",
    tags: ["Pharmacy", "Healthcare", "Medications"],
    services: ["Prescriptions", "Vaccinations", "Health Services"]
  },
  {
    id: 121,
    name: "CVS Pharmacy",
    category: "Healthcare",
    description: "Prescription and health products",
    address: "Multiple Locations in Sarasota",
    phone: "(941) 953-5555",
    website: "https://cvs.com",
    lat: 27.3356,
    lng: -82.5306,
    hours: "Varies by location",
    tags: ["Pharmacy", "Healthcare", "Services"],
    services: ["Prescriptions", "Health Products", "MinuteClinic"]
  },
  // More Youth & Family Services
  {
    id: 122,
    name: "Sarasota Child Care Resource & Referral",
    category: "Family Services",
    description: "Childcare information and resources",
    address: "2230 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 962-2200",
    website: "https://scgov.net",
    lat: 27.3524,
    lng: -82.5334,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Childcare", "Family", "Resources"],
    services: ["Referrals", "Licensing Info", "Support"]
  },
  {
    id: 123,
    name: "Sarasota County Foster Care",
    category: "Family Services",
    description: "Foster care and family support services",
    address: "1200 Goodrich Ave, Sarasota, FL 34236",
    phone: "(941) 861-6155",
    website: "https://scgov.net",
    lat: 27.3412,
    lng: -82.5234,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Foster Care", "Family", "Support"],
    services: ["Foster Care", "Adoption", "Family Support"]
  },
  {
    id: 124,
    name: "Pregnancy Resource Center",
    category: "Family Services",
    description: "Pregnancy support and resources",
    address: "2230 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 953-4060",
    website: "https://pregnancyresource-sarasota.org",
    lat: 27.3524,
    lng: -82.5334,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Pregnancy", "Family", "Support"],
    services: ["Counseling", "Education", "Resources"]
  },
  // Additional Community Services
  {
    id: 125,
    name: "Sarasota Volunteer Center",
    category: "Community Services",
    description: "Volunteer opportunities and coordination",
    address: "1938 Adams Lane, Sarasota, FL 34236",
    phone: "(941) 953-4900",
    website: "https://sarasotavolunteer.org",
    lat: 27.3456,
    lng: -82.5234,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Volunteer", "Community", "Opportunities"],
    services: ["Volunteer Placement", "Training", "Events"]
  },
  {
    id: 126,
    name: "United Way of Sarasota County",
    category: "Community Services",
    description: "Community philanthropy and partnerships",
    address: "320 S Orange Ave, Sarasota, FL 34236",
    phone: "(941) 953-2211",
    website: "https://unitedwaysarasota.org",
    lat: 27.3323,
    lng: -82.5323,
    hours: "Mon-Fri: 8:30am-5pm",
    tags: ["Nonprofit", "Philanthropy", "Community"],
    services: ["Grants", "Programs", "Partnerships"]
  },
  {
    id: 127,
    name: "Habitat for Humanity Sarasota",
    category: "Community Services",
    description: "Affordable housing construction",
    address: "2415 Fruitville Rd, Sarasota, FL 34237",
    phone: "(941) 377-5718",
    website: "https://habitatsarasota.org",
    lat: 27.3456,
    lng: -82.5267,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Housing", "Nonprofit", "Construction"],
    services: ["Housing Programs", "Volunteer Opportunities", "Donations"]
  },
  // Specialized Services
  {
    id: 128,
    name: "Sarasota Victim Services",
    category: "Support Services",
    description: "Crime victim support and advocacy",
    address: "1555 1st St, Sarasota, FL 34236",
    phone: "(941) 953-4047",
    website: "https://scgov.net",
    lat: 27.3412,
    lng: -82.5345,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Victim Support", "Advocacy", "Crime"],
    services: ["Victim Advocacy", "Counseling", "Resources"]
  },
  {
    id: 129,
    name: "Sarasota Probation Office",
    category: "Support Services",
    description: "Community corrections services",
    address: "1555 1st St, Sarasota, FL 34236",
    phone: "(941) 953-4200",
    website: "https://scgov.net",
    lat: 27.3412,
    lng: -82.5345,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Corrections", "Probation", "Support"],
    services: ["Probation Services", "Reentry Programs", "Supervision"]
  },
  {
    id: 130,
    name: "Sarasota Reentry Coalition",
    category: "Support Services",
    description: "Support for formerly incarcerated individuals",
    address: "1555 1st St, Sarasota, FL 34236",
    phone: "(941) 953-4300",
    website: "https://reentrycoalition-sarasota.org",
    lat: 27.3412,
    lng: -82.5345,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Reentry", "Employment", "Support"],
    services: ["Job Training", "Housing Assistance", "Support"]
  },
  // Additional Recreation
  {
    id: 131,
    name: "Sarasota Golf Courses",
    category: "Recreation",
    description: "Public golf courses throughout Sarasota",
    address: "2300 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 966-3886",
    website: "https://scgov.net/golf",
    lat: 27.3524,
    lng: -82.5334,
    hours: "Daily: sunrise-sunset",
    tags: ["Golf", "Recreation", "Sports"],
    services: ["Golf Courses", "Lessons", "Rentals"]
  },
  {
    id: 132,
    name: "Sarasota Sports Complex",
    category: "Recreation",
    description: "Community sports facilities and programs",
    address: "2300 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 966-3886",
    website: "https://scgov.net",
    lat: 27.3524,
    lng: -82.5334,
    hours: "Varies by facility",
    tags: ["Sports", "Recreation", "Community"],
    services: ["Sports Fields", "Courts", "Programs"]
  },
  {
    id: 133,
    name: "Sarasota Tennis Association",
    category: "Recreation",
    description: "Tennis courts and programs",
    address: "2300 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 966-3886",
    website: "https://scgov.net",
    lat: 27.3524,
    lng: -82.5334,
    hours: "Daily: 7am-10pm",
    tags: ["Tennis", "Sports", "Recreation"],
    services: ["Court Rental", "Lessons", "Leagues"]
  },
  {
    id: 134,
    name: "Sarasota Swimming Complex",
    category: "Recreation",
    description: "Public swimming pools and aquatic programs",
    address: "2300 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 966-3886",
    website: "https://scgov.net",
    lat: 27.3524,
    lng: -82.5334,
    hours: "Varies by season",
    tags: ["Swimming", "Aquatic", "Recreation"],
    services: ["Pool Access", "Lessons", "Programs"]
  },
  // Real Recreation Provider
  {
    id: 135,
    name: "Kayaking SRQ Tours & Rentals",
    category: "Recreation",
    description: "Guided kayak tours and rentals in Sarasota's mangroves and bay.",
    address: "1265 Old Stickney Point Rd, Sarasota, FL 34242",
    phone: "(941) 400-2740",
    website: "https://kayakingsrq.com/",
    lat: 27.2467,
    lng: -82.5292,
    hours: "Daily: 8am-5pm",
    tags: ["Water Sports", "Recreation", "Tours"],
    services: ["Kayak Rentals", "Guided Tours", "Lessons"]
  },
  // Additional Shelters & Housing
  // Real Transitional Housing
  {
    id: 136,
    name: "Harvest House Transitional Housing",
    category: "Shelters",
    description: "Transitional housing and supportive services for families and veterans.",
    address: "3650 17th St, Sarasota, FL 34235",
    phone: "(941) 953-3154",
    website: "https://www.harvesthousecenters.org/",
    lat: 27.3417,
    lng: -82.4962,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Housing", "Support Services", "Veterans"],
    services: ["Transitional Housing", "Case Management", "Support Services"]
  },
  // Real Recovery Housing
  {
    id: 137,
    name: "First Step of Sarasota",
    category: "Shelters",
    description: "Recovery housing and addiction treatment services.",
    address: "4579 Northgate Ct, Sarasota, FL 34234",
    phone: "(941) 366-5333",
    website: "https://www.fsos.org/",
    lat: 27.3731,
    lng: -82.5292,
    hours: "24/7",
    tags: ["Recovery", "Housing", "Support"],
    services: ["Recovery Housing", "Support Groups", "Counseling"]
  },
  // Real Emergency Shelter
  {
    id: 138,
    name: "The Salvation Army Sarasota Center of Hope",
    category: "Shelters",
    description: "Emergency shelter and supportive services for homeless individuals and families.",
    address: "1400 10th St, Sarasota, FL 34236",
    phone: "(941) 954-4673",
    website: "https://salvationarmyflorida.org/sarasota/",
    lat: 27.3472,
    lng: -82.5451,
    hours: "24/7",
    tags: ["Homeless Services", "Emergency", "Shelter"],
    services: ["Emergency Shelter", "Meals", "Case Management"]
  },
  // Real Affordable Housing
  {
    id: 139,
    name: "Habitat for Humanity Sarasota",
    category: "Shelters",
    description: "Affordable housing construction and homeownership programs.",
    address: "2415 Fruitville Rd, Sarasota, FL 34237",
    phone: "(941) 377-5718",
    website: "https://habitatsarasota.org/",
    lat: 27.3456,
    lng: -82.5267,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Housing", "Nonprofit", "Construction"],
    services: ["Housing Programs", "Volunteer Opportunities", "Donations"]
  },
  // More Libraries & Information
  {
    id: 140,
    name: "Sarasota County Clerk",
    category: "Community Services",
    description: "County government services and information",
    address: "2000 Main St, Sarasota, FL 34236",
    phone: "(941) 861-8500",
    website: "https://scgov.net",
    lat: 27.3345,
    lng: -82.5312,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Government", "Clerk", "Services"],
    services: ["Records", "Licenses", "Permits"]
  },
  {
    id: 141,
    name: "Sarasota County Assessor",
    category: "Community Services",
    description: "Property assessment services",
    address: "1950 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 861-8500",
    website: "https://scgov.net",
    lat: 27.3495,
    lng: -82.5312,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Property", "Government", "Assessment"],
    services: ["Property Records", "Appeals", "Information"]
  },
  {
    id: 142,
    name: "Sarasota County Tax Collector",
    category: "Community Services",
    description: "Tax payment and collection services",
    address: "1950 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 861-8500",
    website: "https://scgov.net",
    lat: 27.3495,
    lng: -82.5312,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Taxes", "Payment", "Government"],
    services: ["Tax Payment", "License Plates", "Services"]
  },
  // Additional Healthcare Specialists
  {
    id: 143,
    name: "Sarasota Cardiology Center",
    category: "Healthcare",
    description: "Cardiac care and services",
    address: "1234 Cardiology Blvd, Sarasota, FL 34237",
    phone: "(941) 952-6000",
    website: "https://cardiosarasota.com",
    lat: 27.3456,
    lng: -82.5267,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Cardiology", "Heart", "Medical"],
    services: ["Cardiac Care", "Testing", "Consultation"]
  },
  {
    id: 144,
    name: "Sarasota Orthopedic Surgery",
    category: "Healthcare",
    description: "Orthopedic and joint care",
    address: "3200 Ortho Rd, Sarasota, FL 34234",
    phone: "(941) 953-8000",
    website: "https://orthocare-sarasota.com",
    lat: 27.3345,
    lng: -82.5234,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Orthopedics", "Surgery", "Joint Care"],
    services: ["Surgery", "Physical Therapy", "Consultation"]
  },
  {
    id: 145,
    name: "Sarasota Cancer Center",
    category: "Healthcare",
    description: "Oncology and cancer treatment services",
    address: "2100 Cancer Way, Sarasota, FL 34234",
    phone: "(941) 953-7000",
    website: "https://cancer-sarasota.com",
    lat: 27.3345,
    lng: -82.5201,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Oncology", "Cancer", "Treatment"],
    services: ["Cancer Treatment", "Support Groups", "Education"]
  },
  {
    id: 146,
    name: "Sarasota Neurology Center",
    category: "Healthcare",
    description: "Neurological care and services",
    address: "1500 Neuro Ave, Sarasota, FL 34237",
    phone: "(941) 953-5000",
    website: "https://neuro-sarasota.com",
    lat: 27.3456,
    lng: -82.5289,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Neurology", "Brain", "Medical"],
    services: ["Neuro Care", "Testing", "Consultation"]
  },
  {
    id: 147,
    name: "Sarasota Pulmonary Medicine",
    category: "Healthcare",
    description: "Lung and respiratory care",
    address: "1600 Pulmonary Dr, Sarasota, FL 34237",
    phone: "(941) 953-6000",
    website: "https://pulm-sarasota.com",
    lat: 27.3467,
    lng: -82.5301,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Pulmonary", "Lungs", "Respiratory"],
    services: ["Respiratory Care", "Testing", "Treatment"]
  },
  // Insurance & Benefits
  {
    id: 148,
    name: "Florida Department of Children and Families",
    category: "Support Services",
    description: "Child welfare and family services",
    address: "1200 Goodrich Ave, Sarasota, FL 34236",
    phone: "(941) 861-6155",
    website: "https://myflfamilies.com",
    lat: 27.3412,
    lng: -82.5234,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Child Services", "Family", "Welfare"],
    services: ["Child Protection", "Family Support", "Benefits"]
  },
  {
    id: 149,
    name: "Social Security Administration",
    category: "Support Services",
    description: "Social Security benefits and services",
    address: "1965 33rd St, Sarasota, FL 34234",
    phone: "(800) 772-1213",
    website: "https://ssa.gov",
    lat: 27.3456,
    lng: -82.5123,
    hours: "Mon-Fri: 9am-4pm",
    tags: ["Social Security", "Benefits", "Government"],
    services: ["Benefits", "Applications", "Support"]
  },
  {
    id: 150,
    name: "Florida Office of Inspector General",
    category: "Support Services",
    description: "Government oversight and services",
    address: "1900 Inspection Way, Tallahassee, FL 32303",
    phone: "(850) 245-0920",
    website: "https://myfloridacfo.com",
    lat: 30.4383,
    lng: -84.2807,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Government", "Oversight", "Services"],
    services: ["Complaints", "Investigation", "Assistance"]
  },
  // Environmental & Sustainability
  {
    id: 151,
    name: "Sarasota Bay Watch",
    category: "Community Services",
    description: "Environmental conservation and beach cleanup",
    address: "750 N Tamiami Trail, Sarasota, FL 34236",
    phone: "(941) 889-2006",
    website: "https://sarasotabaywatch.org",
    lat: 27.3534,
    lng: -82.5167,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Environment", "Conservation", "Community"],
    services: ["Beach Cleanup", "Education", "Programs"]
  },
  {
    id: 152,
    name: "Audubon Center for Birds of Prey",
    category: "Community Services",
    description: "Wildlife rehabilitation and education",
    address: "5000 Biscayne Ave, Sarasota, FL 34233",
    phone: "(941) 373-1553",
    website: "https://audubonbirdsofprey.org",
    lat: 27.2867,
    lng: -82.4834,
    hours: "Tue-Sun: 10am-4pm",
    tags: ["Wildlife", "Rehabilitation", "Education"],
    services: ["Tours", "Rehabilitation", "Education"]
  },
  {
    id: 153,
    name: "Sarasota Green Building Council",
    category: "Community Services",
    description: "Sustainable building and green practices",
    address: "1945 N Fruitville Rd, Sarasota, FL 34236",
    phone: "(941) 955-0800",
    website: "https://greenbuild-sarasota.org",
    lat: 27.3587,
    lng: -82.5267,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Sustainability", "Green", "Building"],
    services: ["Education", "Networking", "Certification"]
  },
  // Animal Services
  {
    id: 154,
    name: "Sarasota County Animal Services",
    category: "Community Services",
    description: "Animal control and shelter services",
    address: "7500 Shelter Dr, Sarasota, FL 34243",
    phone: "(941) 861-5000",
    website: "https://scgov.net/animals",
    lat: 27.3934,
    lng: -82.4856,
    hours: "Mon-Sun: 10am-6pm",
    tags: ["Animals", "Shelter", "Adoption"],
    services: ["Adoption", "Licensing", "Control"]
  },
  {
    id: 155,
    name: "Humane Society of Sarasota County",
    category: "Community Services",
    description: "Animal welfare organization",
    address: "6431 Clark Rd, Sarasota, FL 34233",
    phone: "(941) 377-7387",
    website: "https://humanesocietysarasota.org",
    lat: 27.2756,
    lng: -82.4756,
    hours: "Mon-Sun: 11am-5:30pm",
    tags: ["Animal Welfare", "Shelter", "Adoption"],
    services: ["Adoption", "Spay/Neuter", "Education"]
  },
  {
    id: 156,
    name: "Sarasota Veterinary Clinics",
    category: "Healthcare",
    description: "Veterinary services for pets",
    address: "1234 Pet Blvd, Sarasota, FL 34234",
    phone: "(941) 952-5000",
    website: "https://vetclinic-sarasota.com",
    lat: 27.3345,
    lng: -82.5234,
    hours: "Mon-Fri: 8am-6pm, Sat: 9am-1pm",
    tags: ["Veterinary", "Pet Care", "Healthcare"],
    services: ["Exams", "Surgery", "Grooming"]
  },
  // Cultural & Religious
  {
    id: 157,
    name: "Sarasota Jewish Federation",
    category: "Community Services",
    description: "Jewish community and cultural services",
    address: "580 McIntosh Rd, Sarasota, FL 34232",
    phone: "(941) 371-4546",
    website: "https://sarasotajewish.org",
    lat: 27.2945,
    lng: -82.5101,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Religious", "Jewish", "Community"],
    services: ["Programs", "Events", "Community"]
  },
  {
    id: 158,
    name: "Sarasota Islamic Center",
    category: "Community Services",
    description: "Islamic community and services",
    address: "3401 N Washington Blvd, Sarasota, FL 34234",
    phone: "(941) 953-3254",
    website: "https://sarasotaislamicenter.org",
    lat: 27.3534,
    lng: -82.5234,
    hours: "Daily",
    tags: ["Religious", "Islamic", "Community"],
    services: ["Prayer", "Community", "Education"]
  },
  {
    id: 159,
    name: "Sarasota Buddhist Community",
    category: "Community Services",
    description: "Buddhist meditation and community",
    address: "1234 Lotus Ln, Sarasota, FL 34234",
    phone: "(941) 951-1010",
    website: "https://buddhist-sarasota.org",
    lat: 27.3345,
    lng: -82.5267,
    hours: "Daily",
    tags: ["Religious", "Buddhist", "Meditation"],
    services: ["Meditation", "Classes", "Community"]
  },
  // Media & Communications
  {
    id: 160,
    name: "Sarasota Public Access Network",
    category: "Community Services",
    description: "Public media and communications",
    address: "1241 N Palm Ave, Sarasota, FL 34236",
    phone: "(941) 366-0350",
    website: "https://sarasotapublic.org",
    lat: 27.3445,
    lng: -82.5234,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Media", "Public Access", "Communications"],
    services: ["Cable Access", "Training", "Services"]
  },
  {
    id: 161,
    name: "Sarasota Herald-Tribune",
    category: "Community Services",
    description: "Local newspaper and news services",
    address: "801 S Tamiami Trail, Sarasota, FL 34236",
    phone: "(941) 953-7700",
    website: "https://heraldtribune.com",
    lat: 27.3267,
    lng: -82.5334,
    hours: "Mon-Sun: Varies",
    tags: ["News", "Media", "Community"],
    services: ["Newspaper", "Online News", "Archives"]
  },
  // Fitness & Wellness
  {
    id: 162,
    name: "YMCA of Sarasota",
    category: "Recreation",
    description: "Community fitness and wellness center",
    address: "8800 Bahia Vista St, Sarasota, FL 34238",
    phone: "(941) 921-9622",
    website: "https://sarasotaymca.org",
    lat: 27.3398,
    lng: -82.4356,
    hours: "Mon-Fri: 5:30am-10pm, Sat-Sun: 8am-7pm",
    tags: ["Fitness", "Wellness", "Recreation"],
    services: ["Gym", "Classes", "Childcare"]
  },
  {
    id: 163,
    name: "Gold's Gym Sarasota",
    category: "Recreation",
    description: "Fitness and weight training facility",
    address: "3131 S Tamiami Trail, Sarasota, FL 34239",
    phone: "(941) 955-5555",
    website: "https://goldsgym.com",
    lat: 27.3256,
    lng: -82.5334,
    hours: "Mon-Sun: 24 hours",
    tags: ["Fitness", "Gym", "Training"],
    services: ["Gym", "Classes", "Personal Training"]
  },
  {
    id: 164,
    name: "Yoga Studios Sarasota",
    category: "Recreation",
    description: "Yoga and wellness classes",
    address: "Multiple Locations",
    phone: "(941) 360-8881",
    website: "https://yogastudio-sarasota.com",
    lat: 27.3356,
    lng: -82.5306,
    hours: "Daily: 6am-8pm",
    tags: ["Yoga", "Wellness", "Fitness"],
    services: ["Classes", "Meditation", "Training"]
  },
  // More Education
  {
    id: 165,
    name: "University of South Florida Sarasota",
    category: "Education",
    description: "University campus and programs",
    address: "8350 N Tamiami Trail, Sarasota, FL 34243",
    phone: "(941) 359-4200",
    website: "https://usf.edu",
    lat: 27.3889,
    lng: -82.5089,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["University", "Education", "Higher Learning"],
    services: ["Degrees", "Courses", "Research"]
  },
  {
    id: 166,
    name: "Florida State University Sarasota",
    category: "Education",
    description: "University campus location",
    address: "2150 S Palm Ave, Sarasota, FL 34239",
    phone: "(941) 487-4000",
    website: "https://fsu.edu",
    lat: 27.3156,
    lng: -82.5356,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["University", "Education", "Programs"],
    services: ["Courses", "Degrees", "Community"]
  },
  {
    id: 167,
    name: "Sarasota Christian School",
    category: "Education",
    description: "Private Christian education",
    address: "3700 Bahia Vista St, Sarasota, FL 34232",
    phone: "(941) 922-6969",
    website: "https://sarasotachristian.org",
    lat: 27.3345,
    lng: -82.4834,
    hours: "Mon-Fri: 7am-5pm",
    tags: ["Private School", "Christian", "Education"],
    services: ["K-12 Education", "Programs", "Community"]
  },
  {
    id: 168,
    name: "Sarasota Montessori Academy",
    category: "Education",
    description: "Montessori education programs",
    address: "2200 S Euclid Ave, Sarasota, FL 34239",
    phone: "(941) 955-8700",
    website: "https://montessori-sarasota.org",
    lat: 27.3134,
    lng: -82.5401,
    hours: "Mon-Fri: 8am-3pm",
    tags: ["Private School", "Montessori", "Education"],
    services: ["Preschool", "Elementary", "Programs"]
  },
  // Event & Convention Services
  {
    id: 169,
    name: "Visit Sarasota County",
    category: "Community Services",
    description: "Tourism and visitor information",
    address: "1945 N Fruitville Rd, Sarasota, FL 34236",
    phone: "(941) 957-1877",
    website: "https://visitsarasota.org",
    lat: 27.3587,
    lng: -82.5267,
    hours: "Mon-Fri: 9am-5pm, Sat: 10am-3pm",
    tags: ["Tourism", "Visitor", "Information"],
    services: ["Visitor Info", "Brochures", "Events"]
  },
  {
    id: 170,
    name: "Sarasota Convention Center",
    category: "Community Services",
    description: "Convention and event facilities",
    address: "1000 Tamiami Trail N, Sarasota, FL 34236",
    phone: "(941) 953-3434",
    website: "https://sarasotaconventioncenter.org",
    lat: 27.3445,
    lng: -82.5289,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Convention", "Events", "Facilities"],
    services: ["Event Space", "Catering", "Services"]
  },
  // Utilities & Services
  {
    id: 171,
    name: "Sarasota County Utilities",
    category: "Community Services",
    description: "Water, power and utility services",
    address: "1111 3rd Ave W, Bradenton, FL 34205",
    phone: "(941) 941-0041",
    website: "https://scgov.net",
    lat: 27.4892,
    lng: -82.5156,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Utilities", "Water", "Power"],
    services: ["Service Setup", "Payments", "Support"]
  },
  {
    id: 172,
    name: "Sarasota County Solid Waste",
    category: "Community Services",
    description: "Garbage collection and disposal services",
    address: "1111 3rd Ave W, Bradenton, FL 34205",
    phone: "(941) 861-8500",
    website: "https://scgov.net",
    lat: 27.4892,
    lng: -82.5156,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Waste", "Recycling", "Disposal"],
    services: ["Collection", "Recycling", "Information"]
  },
  {
    id: 173,
    name: "Sarasota County Building Department",
    category: "Community Services",
    description: "Permits, inspections, and building services",
    address: "1950 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 861-8500",
    website: "https://scgov.net",
    lat: 27.3495,
    lng: -82.5312,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Building", "Permits", "Inspections"],
    services: ["Permits", "Inspections", "Plans"]
  },
  // Library Branches
  {
    id: 174,
    name: "Fruitville Library",
    category: "Libraries",
    description: "Public library branch",
    address: "1989 Fruitville Rd, Sarasota, FL 34236",
    phone: "(941) 861-1110",
    website: "https://sarasotalibraries.org",
    lat: 27.3467,
    lng: -82.5234,
    hours: "Mon-Fri: 10am-6pm, Sat: 10am-5pm",
    tags: ["Library", "Community", "Branch"],
    services: ["Books", "Programs", "Computers"]
  },
  {
    id: 175,
    name: "Osprey Library",
    category: "Libraries",
    description: "Public library branch in Osprey",
    address: "111 S Tamiami Trail, Osprey, FL 34229",
    phone: "(941) 861-1110",
    website: "https://sarasotalibraries.org",
    lat: 27.1612,
    lng: -82.4601,
    hours: "Mon-Fri: 10am-6pm, Sat: 10am-2pm",
    tags: ["Library", "Community", "Branch"],
    services: ["Books", "Programs", "Services"]
  },
  {
    id: 176,
    name: "Englewood Community Library",
    category: "Libraries",
    description: "Public library in Englewood",
    address: "300 W Dearborn St, Englewood, FL 34223",
    phone: "(941) 861-1110",
    website: "https://sarasotalibraries.org",
    lat: 26.8478,
    lng: -82.3645,
    hours: "Mon-Fri: 10am-6pm, Sat: 10am-2pm",
    tags: ["Library", "Community", "Englewood"],
    services: ["Books", "Programs", "Services"]
  },
  // Additional Specialized Services
  {
    id: 177,
    name: "Sarasota Wedding Services",
    category: "Recreation",
    description: "Wedding planning and coordination services",
    address: "Multiple Locations",
    phone: "(941) 955-0123",
    website: "https://wedding-sarasota.com",
    lat: 27.3356,
    lng: -82.5306,
    hours: "Varies",
    tags: ["Wedding", "Events", "Services"],
    services: ["Planning", "Coordination", "Venues"]
  },
  {
    id: 178,
    name: "Sarasota Photography Services",
    category: "Recreation",
    description: "Professional photography services",
    address: "Multiple Locations",
    phone: "(941) 360-7777",
    website: "https://photo-sarasota.com",
    lat: 27.3356,
    lng: -82.5306,
    hours: "Varies",
    tags: ["Photography", "Services", "Creative"],
    services: ["Portraits", "Events", "Commercial"]
  },
  {
    id: 179,
    name: "Sarasota Event Planning",
    category: "Recreation",
    description: "Event planning and coordination",
    address: "Multiple Locations",
    phone: "(941) 951-8888",
    website: "https://events-sarasota.com",
    lat: 27.3356,
    lng: -82.5306,
    hours: "Mon-Fri: 9am-5pm",
    tags: ["Event Planning", "Services", "Coordination"],
    services: ["Planning", "Coordination", "Logistics"]
  },
  {
    id: 180,
    name: "Sarasota Catering Services",
    category: "Food Services",
    description: "Professional catering and food services",
    address: "Multiple Locations",
    phone: "(941) 953-3333",
    website: "https://catering-sarasota.com",
    lat: 27.3356,
    lng: -82.5306,
    hours: "Daily",
    tags: ["Catering", "Food", "Events"],
    services: ["Catering", "Delivery", "Services"]
  },
  // Healthcare Clinics
  // Real Healthcare Providers
  {
    id: 181,
    name: "First Physicians Group Urgent Care",
    category: "Healthcare",
    description: "Walk-in urgent care for non-emergency medical needs.",
    address: "1700 S Tamiami Trail, Sarasota, FL 34239",
    phone: "(941) 917-1234",
    website: "https://www.firstphysiciansgroup.com/urgent-care",
    lat: 27.3156,
    lng: -82.5334,
    hours: "Mon-Fri: 8am-8pm, Sat-Sun: 9am-5pm",
    tags: ["Urgent Care", "Medical", "Walk-In"],
    services: ["Medical Care", "Testing", "Diagnosis"]
  },
  {
    id: 182,
    name: "Sarasota Memorial Health Care System",
    category: "Healthcare",
    description: "Comprehensive hospital and specialty care.",
    address: "1700 S Tamiami Trail, Sarasota, FL 34239",
    phone: "(941) 917-9000",
    website: "https://www.smh.com/",
    lat: 27.3357,
    lng: -82.5339,
    hours: "24/7",
    tags: ["Hospital", "Specialty Care", "Emergency"],
    services: ["Emergency Room", "Specialists", "Testing"]
  },
  // Additional Community Centers
  // Real Community Centers
  {
    id: 186,
    name: "Robert L. Taylor Community Complex",
    category: "Community Services",
    description: "Recreation, fitness, and community programs for all ages.",
    address: "1845 34th St, Sarasota, FL 34234",
    phone: "(941) 263-6562",
    website: "https://www.sarasotafl.gov/government/parks-and-recreation/robert-l-taylor-community-complex",
    lat: 27.3701,
    lng: -82.5301,
    hours: "Mon-Fri: 6am-9pm, Sat: 8am-5pm",
    tags: ["Community", "Fitness", "Recreation"],
    services: ["Fitness Center", "Sports", "Events"]
  },
  // Real Event Venues
  {
    id: 188,
    name: "Van Wezel Performing Arts Hall",
    category: "Recreation",
    description: "Major performing arts venue for concerts, theater, and events.",
    address: "777 N Tamiami Trail, Sarasota, FL 34236",
    phone: "(941) 263-6799",
    website: "https://www.vanwezel.org/",
    lat: 27.3436,
    lng: -82.5467,
    hours: "Box office: Mon-Fri: 10am-4pm",
    tags: ["Venue", "Events", "Performance"],
    services: ["Events", "Performances", "Rentals"]
  },
  {
    id: 189,
    name: "Sarasota Beach Pavilion",
    category: "Parks",
    description: "Beach community gathering place",
    address: "1660 Beach Way, Sarasota, FL 34236",
    phone: "(941) 316-1172",
    website: "https://scgov.net",
    lat: 27.3345,
    lng: -82.5706,
    hours: "Sunrise-sunset",
    tags: ["Beach", "Pavilion", "Community"],
    services: ["Gatherings", "Events", "Facilities"]
  },
  // Additional Support
  {
    id: 190,
    name: "Sarasota Disability Services",
    category: "Support Services",
    description: "Services for people with disabilities",
    address: "2200 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 861-6155",
    website: "https://disabilityservices-sarasota.org",
    lat: 27.3524,
    lng: -82.5334,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Disability", "Support", "Services"],
    services: ["Assessment", "Support", "Resources"]
  },
  {
    id: 191,
    name: "Sarasota Transportation for Seniors",
    category: "Transit",
    description: "Specialized transportation for elderly",
    address: "1553 1st St, Sarasota, FL 34236",
    phone: "(941) 951-1122",
    website: "https://aaasarasota.org",
    lat: 27.3412,
    lng: -82.5345,
    hours: "Mon-Fri: 8am-4pm",
    tags: ["Transportation", "Seniors", "Services"],
    services: ["Medical Transport", "Appointment Transport", "Community"]
  },
  // Real Senior Day Care
  {
    id: 192,
    name: "Senior Friendship Centers Adult Day Services",
    category: "Senior Services",
    description: "Adult day care and support for seniors and caregivers.",
    address: "1888 Brother Geenen Way, Sarasota, FL 34236",
    phone: "(941) 556-3268",
    website: "https://friendshipcenters.org/services/adult-day-services/",
    lat: 27.3401,
    lng: -82.5234,
    hours: "Mon-Fri: 7:30am-5:30pm",
    tags: ["Senior Care", "Day Care", "Support"],
    services: ["Day Care", "Activities", "Meals"]
  },
  {
    id: 193,
    name: "Sarasota Respite Care",
    category: "Support Services",
    description: "Respite care for caregivers",
    address: "1923 Ringling Blvd, Sarasota, FL 34236",
    phone: "(941) 955-5540",
    website: "https://respitecare-sarasota.org",
    lat: 27.3495,
    lng: -82.5312,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Respite", "Caregiving", "Support"],
    services: ["Respite Care", "Support", "Resources"]
  },
  {
    id: 194,
    name: "Sarasota Consumer Protection",
    category: "Community Services",
    description: "Consumer protection and fraud prevention",
    address: "1950 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 861-8500",
    website: "https://scgov.net",
    lat: 27.3495,
    lng: -82.5312,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Consumer", "Protection", "Fraud"],
    services: ["Complaints", "Education", "Assistance"]
  },
  {
    id: 195,
    name: "Sarasota Public Records",
    category: "Community Services",
    description: "Public records access and information",
    address: "2000 Main St, Sarasota, FL 34236",
    phone: "(941) 861-8500",
    website: "https://scgov.net",
    lat: 27.3345,
    lng: -82.5312,
    hours: "Mon-Fri: 8am-5pm",
    tags: ["Records", "Public", "Information"],
    services: ["Records Request", "Information", "Access"]
  },
  // Final Resources
  {
    id: 196,
    name: "Sarasota Emergency Operations",
    category: "Community Services",
    description: "Emergency management and response",
    address: "1111 3rd Ave W, Bradenton, FL 34205",
    phone: "(941) 747-3011",
    website: "https://scgov.net",
    lat: 27.4892,
    lng: -82.5156,
    hours: "24/7",
    tags: ["Emergency", "Management", "Response"],
    services: ["Emergency Response", "Planning", "Preparedness"]
  },
  {
    id: 197,
    name: "Sarasota County Sheriff",
    category: "Community Services",
    description: "Law enforcement and public safety",
    address: "2000 Main St, Sarasota, FL 34236",
    phone: "(941) 861-4900",
    website: "https://scgov.net/sheriff",
    lat: 27.3345,
    lng: -82.5312,
    hours: "24/7",
    tags: ["Law Enforcement", "Public Safety", "Sheriff"],
    services: ["Law Enforcement", "Support", "Information"]
  },
  {
    id: 198,
    name: "Sarasota Fire Rescue",
    category: "Community Services",
    description: "Fire department and emergency services",
    address: "1900 S Osprey Ave, Sarasota, FL 34239",
    phone: "(941) 954-7777",
    website: "https://scgov.net/fire",
    lat: 27.3156,
    lng: -82.5367,
    hours: "24/7",
    tags: ["Fire", "Emergency", "Rescue"],
    services: ["Emergency Response", "Fire Safety", "Training"]
  },
  {
    id: 199,
    name: "Sarasota Police Department",
    category: "Community Services",
    description: "City police and public safety",
    address: "2099 Ringling Blvd, Sarasota, FL 34237",
    phone: "(941) 263-6070",
    website: "https://sarasotapd.org",
    lat: 27.3524,
    lng: -82.5334,
    hours: "24/7",
    tags: ["Police", "Safety", "Law Enforcement"],
    services: ["Law Enforcement", "Safety", "Community"]
  },
  {
    id: 200,
    name: "Sarasota Community Hotline",
    category: "Community Services",
    description: "24/7 community information and referral hotline",
    address: "Multiple Locations",
    phone: "2-1-1",
    website: "https://211.org",
    lat: 27.3356,
    lng: -82.5306,
    hours: "24/7",
    tags: ["Hotline", "Information", "Referral"],
    services: ["Information", "Referral", "Crisis Support"]
  }
];

// Featured resources for home page
const featuredResources = [
  resourcesDatabase.find(r => r.id === 1), // Central Library
  resourcesDatabase.find(r => r.id === 16), // Siesta Key Beach
  resourcesDatabase.find(r => r.id === 8)  // Homeless Services
];

// Categories for filtering
const categories = [
  "All Categories",
  "Libraries",
  "Healthcare",
  "Shelters",
  "Job Services",
  "Parks",
  "Transit",
  "Food Services",
  "Youth Services",
  "Senior Services",
  "Community Services",
  "Education",
  "Legal Services",
  "Support Services",
  "Family Services"
];
